### ISSUE TITLE
jsonb  `#>` and `#>>` operator

### ISSUE THREAD

**Issue by euri10** [encode/databases#104]
was looking at https://github.com/encode/databases/issues/56 and decided to try an attempt at enriching the documentation.

I'm able to get queries running fine for most operators:

-  `->` , ` ->>` work in sqlalchemy core syntax

- but for some reason I can't manage to get `#>` or `#>>` working and get the error below. 

Both  `#>` and `#>>` work fine with raw queries, and ironically if I use the compiled statement generated by sqlalchemy, and use it as a raw query, it's fine as well so the generated sql seems to be correct under the hood

when using sqlalchemy syntax as described [here](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#sqlalchemy.dialects.postgresql.JSON) it fails with 

> asyncpg.exceptions.DataError: invalid input for query argument $1: '{company, name}' (a sized iterable container expected (got type 'str'))

here's a little reproducible snippet

```
jsonitems = sqlalchemy.Table(
    "jsonitems",
    metadata,
    sqlalchemy.Column(
        "id",
        UUID(),
        server_default=text("uuid_generate_v4()"),
        primary_key=True,
        unique=True,
    ),
    sqlalchemy.Column("metadata", JSONB()),
    sqlalchemy.Column(
        "time_created", sqlalchemy.DateTime(timezone=True), server_default=func.now()
    ),
    sqlalchemy.Column(
        "time_updated", sqlalchemy.DateTime(timezone=True), onupdate=func.now()
    ),
)
```
```
     inserts = [
        {"country": "Peru"},
        {"country": "France"},
        {"company": {"name": "Mozilla"}},
        {"company": {"name": "Mozilla"}, "country": "Brazil"},
        {"foo_int": 12345},
        {"a": {"b": {"c": "foo"}}}
    ]
    # for insert in inserts:
    #     jsonitemin = JsonItemIn(metadata=insert)
    #     response = client.post(url, json=jsonitemin.dict())
    #     assert response.status_code == 201

    query = jsonitems.insert()
    r = sync(database.execute_many(query, values=[{"metadata": insert} for insert in inserts]))
    ### Basic select make sure we got all items
    query = select([jsonitems])
    r = sync(database.fetch_all(query))
    assert len(r) == 6

    ### Index operations (the -> operator):

    query = select([jsonitems.c.metadata['country']])
    r = sync(database.fetch_all(query))
    # returns all items
    assert len(r) == 6
    # only 3 of them have the country key
    assert len([l for l in r if l["anon_1"] is not None]) == 3
    assert [l["anon_1"] for l in r if l["anon_1"] is not None] == ['Peru', 'France', 'Brazil']

    ### Index operations returning text (the ->> operator):

    query = select([jsonitems]).where(jsonitems.c.metadata['country'].astext == 'France')
    r = sync(database.fetch_all(query))
    assert len(r) == 1
    assert r[0]['metadata'] == {'country': 'France'}

    ### Index operations with CAST (equivalent to CAST(col ->> ['some key'] AS <type>)):

    query = select([jsonitems]).where(jsonitems.c.metadata['foo_int'].cast(Integer) == 12345)
    r = sync(database.fetch_all(query))
    assert len(r) == 1

    query = select([jsonitems]).where(jsonitems.c.metadata['foo_int'].cast(Integer) == 54321)
    r = sync(database.fetch_all(query))
    assert len(r) == 0

    ### Path index operations (the #> operator):

    queryraw = "SELECT jsonitems.metadata #>'{a,b}' FROM jsonitems;"
    rows = sync(database.fetch_all(query=queryraw))
    query = select([jsonitems.c.metadata[("company", "name")]])
    print(str(query.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True})))
    using_query_sqlalchemy = sync(database.fetch_all(str(query.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))))
    assert len(using_query_sqlalchemy) == 6
    assert [l["anon_1"] for l in using_query_sqlalchemy if l["anon_1"] is not None] ==  ['"Mozilla"', '"Mozilla"']
    r = sync(database.fetch_all(query))
```

**Comment by euri10** [comment]
Not sure if it's a bug upstream or here in fact, but to add to the siscussion:

under the hood it seems databases will do a `await conn.fetch(q, *args)`

the below snippet attempts to do the same with just asyncpg, and it throws throws the same error while raw sql queries are ok

so I have no idea if it's a mis use on my end ot the fetch below but databases seems to use the exact same query, args 

```
async def run():
    conn = await asyncpg.connect(user='postgres', password='postgres',
                                 database='postgres', host='db', port ='5432')

    values = await conn.fetch('''SELECT jsonitems.metadata #>'{a,b}' AS anon_1 FROM jsonitems;''')
    print(values)

    query = select([jsonitems.c.metadata[("a", "b")]])
    compiled = (str(query.compile(dialect=postgresql.dialect(),
                            compile_kwargs={"literal_binds": True})))
    print(compiled)
    values = await conn.fetch(compiled)
    print(values)

    q= 'SELECT jsonitems.metadata #> $1 AS anon_1 FROM jsonitems'
    args = ['{a, b}']
    values = await conn.fetch(q, *args)
    await conn.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

**Comment by euri10** [comment]
to sum it up, the `query` below yields an error in asyncpg

```
query = select([jsonitems.c.metadata[("a", "b")]])
r = sync(database.fetch_all(query))
```

with logging turned on I get from https://github.com/encode/databases/blob/c008b2af890d245f35d27d42f5851d329ce2d45a/databases/backends/postgres.py#L194
```
Query: SELECT jsonitems.metadata #> $1 AS anon_1 
FROM jsonitems
Args: ['{a, b}']
```

the below snippet works in plain asyncpg, note args in generated sqlalchemy is ` ['{a, b}']` instead of ` [['a', 'b']]` to make it work

```
    q= 'SELECT jsonitems.metadata #> $1 AS anon_1 FROM jsonitems'
    args = [['a', 'b']]
    # args = ['{a, b}']
    values = await conn.fetch(q, *args)
    print(values)
    await conn.close()
```

the compiled sqlalchemy query works fine using a raw statement
```
compiled = (str(query.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True})))

SELECT jsonitems.metadata #> '{a, b}' AS anon_1 FROM jsonitems`

```

so to me it seems there might be an issue in databases in 
https://github.com/encode/databases/blob/c008b2af890d245f35d27d42f5851d329ce2d45a/databases/backends/postgres.py#L189-L192

but I'm not certain, hope the recap helps a little

**Comment by euri10** [comment]
well I ended up adding a failing test case here https://github.com/euri10/databases/blob/63628797bca6b1f417b7193a0cc13b35789cdb60/tests/test_databases.py#L712-L747
will be easier

**Comment by tomchristie** [comment]
Okay, thanks for all this.
I'm going to need you to take the lead if it's something you're invested in resolving, as it's way beyond what I have the scope to dive into right now.
A failing test case would be a great start, yup.

**Comment by euri10** [comment]
want me to PR the branch even if it's failing @tomchristie ? and do you think it's worth cross-posting it to asyncpg, I honestly got no idea if it's here or there :drooling_face:

**Comment by tomchristie** [comment]
> want me to PR the branch even if it's failing @tomchristie ?

A failing test case is a decent place to start yup. Really it depends on if you think you're likely to try taking this on. If no-one's available then I'd likely just close this off as "out of scope, we don't support #> or #>> operators" (Because: what then heck - literally no idea what either of those are, or what cross-database support we'd expect them to have, if any.) 😀

> and do you think it's worth cross-posting it to asyncpg

No idea. You're in a better place to take a call on that than me.

**Comment by euri10** [comment]
ok seems like it's a little bit more complicated than what i thought and even a failing test-case won't help much, after I read also the https://github.com/CanopyTax/asyncpgsa code, it seems their compile method does the same.
the underlying issue is that for right operand of type text[], sqlalchemy core produces an array string litteral that once passed in asyncpg yields an error if things are not cast explicitly.

I didn't find a way in sqlalchemy internals to produce something else than an array string litteral as it's done in 
```
        processors = compiled._bind_processors
        args = [
            processors[key](val) if key in processors else val
            for key, val in compiled_params
        ]
```

So after failing short at solving this I'd suggest using raw queries for that, but I'm sure someone more competent will find a way

I'll nonetheless try to update the docs on queries that can be passed easily with sqlalchemy core,
