### ISSUE TITLE
How to update rows and return effect rows' count

### ISSUE THREAD

**Issue by billsteve** [encode/databases#106]
qurey = t_user_collect_product.update().where(text(f"product_id = {product_id} AND user_id ={user['user_id']}")).values(is_del=1)
res = await  db.execute(qurey)

res always is 0

**Comment by tomchristie** [comment]
I don't know the answer to that, but I'm going to pitch this the other way around:

Is this functionality provided by one or more of the drivers that we're not currently exposing in `databases`? If so which drivers, and how?

If there's functionality in the underlying drivers that we're not adequatly exposing, then we can consider looking into that.
