### ISSUE TITLE
Native decimal support

### ISSUE THREAD

**Issue by coobas** [encode/databases#113]
Hi,
first thank you for this great library. I was missing native decimal support (decimals are rounded) and sketched a solution in https://github.com/encode/databases/pull/112 - seems like it can be safely enabled for Postgres and MySQL. Hope this would be useful for you.
Cheers
Jakub

**Comment by tomchristie** [comment]
Released as 0.2.3.

Thanks!

**Comment by coobas** [comment]
Thanks for the quick merge and release :)
