### ISSUE TITLE
Async sqlite?

### ISSUE THREAD

**Issue by coleifer** [encode/databases#127]
I was curious what it means to present an async interface to Sqlite. My thought is that since Sqlite is an embedded database, there's no socket i/o, which is where one would typically see an event loop entering the picture. There's the additional caveat that only a single connection can hold the write lock at any given time, so you need to either share your connection across threads (adding significant complexity to the atomicity and size of your transactions, since transactions are bound to the connection), or handle the inevitable OperationalErrors from trying to write from multiple connections concurrently.

So what use-case does async sqlite intend to make better? I guess if you had a scraper or something and were hucking the responses from many asynchronous requests into a sqlite db, you could see some improvement (since the stdlib sqlite3 driver releases the GIL in the appropriate places)?

**Comment by coleifer** [comment]
Well, I tracked down a little further and saw aiosqlite has a nice details section on the readme:

> aiosqlite allows interaction with SQLite databases on the main AsyncIO event loop without blocking execution of other coroutines while waiting for queries or data fetches. It does this by using a single, shared thread per connection. This thread executes all actions within a shared request queue to prevent overlapping actions.

Nevermind!

**Comment by tomchristie** [comment]
Yup. Its no more efficientor feature-ful than using the standard driver, but if you're working with an async codebase then you need it.
