### ISSUE TITLE
Rollbacks happen not only on database disconnect, when force_rollback=True 

### ISSUE THREAD

**Issue by FNSdev** [encode/databases#130]
Hello!
I am using _starlette, databases, pytest_ and trying to write some tests, that will have to make sure that objects with specific field values are created in database when request is being processed.

I followed the documentation:
```
if TESTING:
    database = Database(TEST_DATABASE_URL, force_rollback=True)
else:
    database = Database(DATABASE_URL)
```

>This will give you test cases that run against a different database to the development database, with strict test isolation so long as you make sure to connect and disconnect to the database between test cases.

But the problem is that rollbacks are happening not only on database disconnect, but also after something should be inserted in database. 

Because of that, when I try to query my database in a test, there are no objects and assert fails. I am sure, that I am not disconnected from database at this point (it will happen after Starlette`s TestClient leaves test function scope)

![Screenshot from 2019-07-25 14-56-50](https://user-images.githubusercontent.com/29799729/61872617-7af67d80-aeec-11e9-8818-11e81efd5848.png)

Is it working as intended or am I doing something wrong?

**Comment by tomchristie** [comment]
Perhaps something to do with being already inside the transaction during the test case, so the operations havn't actually been commited yet?

**Comment by FNSdev** [comment]
Thank you for the reply!

I think you are right, because i do not commit anything manually, so the problem is not about rollbacks. I`m sorry for misleading you.

Could you please give me an advice on how to implement functionality that I need? Maybe it would be easier to truncate all tables on each test case?

**Comment by tomchristie** [comment]
It might be worth asking on the (new) [discussion group](https://discuss.encode.io/c/databases) to see if anyone else has had issues with getting the patterns right for testing database operations.

You could also try asking on the FastAPI gitter channel https://gitter.im/tiangolo/fastapi

**Comment by gvbgduh** [comment]
@FNSdev you have several variables to play with. It really depends on your code structure, but there're some options to combine:

1. you can define the db without forced_rollback
```
database = Database(TEST_DATABASE_URL)
```
2. Play with the scopes in pytest
the example shows
```
@pytest.fixture(scope="session", autouse=True)
def create_test_database():
```
it means the db created once for the whole test session, you can also define per module or per test.

So, if you instantiate the db without forced_rollback, you might like to clean the db after every test or manage the data from previous.

Please note, that re-creation the db for every test is expensive operation and seriously increases the time for tests run, it's also a place where you can truncate tables, which maybe much faster than the whole recreation.

**Comment by FNSdev** [comment]
Thank you so much for answering! I decided to truncate my tables on every test case for now. I agree that recreating database everytime is not a good option, so it is created once per tests tun
