### ISSUE TITLE
Why PostgresBackend uses the pypostgresql instead of psycopg2?

### ISSUE THREAD

**Issue by mpyatishev** [encode/databases#136]
The question is: why PostgresBackend uses the pypostgresql instead of psycopg2?

**Comment by tomchristie** [comment]
It doesn't use either - it uses `asyncpg`.

It looks like we happen to import and use `pypostgresql` as the base of the dialect description. I've no idea if that's the right thing to do there, or if psycopg2 would be a closer match to `asyncpg`. We just [cribbing the same style as the `asyncpgsa` package](https://github.com/CanopyTax/asyncpgsa/blob/2607565ab645b5ef9e03283495257442e9c9c22a/asyncpgsa/connection.py#L11). See https://github.com/CanopyTax/asyncpgsa/pull/23 for when they first switched to that dialect.

**Comment by mpyatishev** [comment]
Thanks for your answer. I try to figure out why i've got an exception when result contains the UUID:
```
  File "/home/max/work/indigo-backend/env/lib/python3.7/site-packages/databases/backends/postgres.py", line 114, in __getitem__
    return processor(raw)
  File "/home/max/work/indigo-backend/env/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1257, in process
    return process_value(impl_processor(value), dialect)
  File "/home/max/work/indigo-backend/env/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 943, in process
    value = bytes(value)
TypeError: cannot convert 'UUID' object to bytes
```
It is the same issue as in the #88.
And I thought the reason might be in the chosen dialect.
