### ISSUE TITLE
How to check if .execute(.) went through ?

### ISSUE THREAD

**Issue by gillesdegottex** [encode/databases#142]
Hi,

I've check the doc and the code, though I can't find a way to check if .execute(.) went through.
E.g. with a delete query type, where there is nothing to fetch.

Any idea?

Cheers,

**Comment by steinitzu** [comment]
You mean to get e.g. the row count? I'm not sure if that's exposed, if it is it's probably just the return value of `execute()` (I know it returns the last row id for inserts).

If you mean you just want to know whether the query errored or not, you get an exception if it fails.

**Comment by dmontagu** [comment]
I have a function like this:
```python
async def delete_by_columns_values(
    database: Database, table: sa.Table, columns: AnyCols, values: AnyTuples, pk_columns: List["sa.Column[Any]"]
) -> List[Any]:
    assert all(len(value) == len(columns) for value in values)
    query = table.delete().where(sa.tuple_(*columns).in_(values)).returning(*pk_columns)
    return await database.execute(query)
```
Note: I think the above is postgres-specific -- if I recall correctly, sqlite didn't support this API.

I'm not sure if there is a way to just determine the row count of deleted rows if using sqlite -- it looks like there are special functions to do this in the sqlite package but I'm not sure the functionality is exposed through databases (and at any rate it would probably not be easy to make it portable to other backends).

**Comment by gillesdegottex** [comment]
Yes, sort of a row count.
Though I guess I can rely on the exception.
`execute ()` returns me `0` for delete operations.

**Comment by tomchristie** [comment]
Seconding @dmontagu - you probably want a `RETURNING` clause.
See also #61, #101.

**Comment by gvbgduh** [comment]
As a possible workaround or if you want the full lower level control, there's the allocated interface to access the raw driver as

```
async with database.connection() as connection:
    raw_connection = connection.raw_connection
         status = await raw_connection.copy_records_to_table(...)
```
Then depending on the driver you can utilize its API as is.
But, raw access also means raw response from the DB.

**Comment by gnat** [comment]
Patch featuring the correct behavior is here: https://github.com/encode/databases/pull/150

@gillesdegottex

**Comment by gillesdegottex** [comment]
Thanks a lot !
