### ISSUE TITLE
How to limit number of concurrent requests ?

### ISSUE THREAD

**Issue by leafonsword** [encode/databases#159]
aiohttp could limit number of concurrent requests by `aiohttp.TCPConnector(limit=3)`, https://stackoverflow.com/questions/50190480/limit-number-of-concurrent-requests-aiohttp

Does databases could also limit ?

**Comment by tomchristie** [comment]
The [connection pooling](https://www.encode.io/databases/connections_and_transactions/#connection-options) will limit the number of concurrent database connections, yes.
