### ISSUE TITLE
Bulk insert not supported?

### ISSUE THREAD

**Issue by jmagnusson** [encode/databases#170]
Is there currently no support in `databases` for executing one statement that inserts multiple values?

Looking at the source code `execute` only accepts a `dict` (i.e. insert one row) and `execute_many` turns into one executed statement per member of the passed in `values` parameter.

https://github.com/encode/databases/blob/f916dbbedceb0740c3708251c90a4f84108c3757/databases/core.py#L236-L247

**Comment by xobb1t** [comment]
@jmagnusson to prevent execution multiple inserts you can try to construct query like that:

```python
query = table.insert().values([
    {'column_name': val1},
    {'column_name': val2},
])
await database.execute(query)
```

**Comment by tomchristie** [comment]
It's up to the individual database-specific implementation to determine how to handle `execute_many`.
Eg... https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L182

We'd happily accept pull requests that switch an implementation over to using driver-supported bulk executes. Eg. it looks like asyncpg provides this... https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.Connection.executemany

However I don't have time to prioritize this myself, so it'd be up to individual contributors to issue a pull request if anyone's keen to see it move forward.
