### ISSUE TITLE
[QUESTION] Raw Query IN clause list?

### ISSUE THREAD

**Issue by neilpanchal** [encode/databases#171]
How can I do the following:

```python

# Input list of bar_ids
bar_ids_input = [1, 2, 3, 4]

# Convert to dictionary mapping
bar_ids = [{'bar_id': bar_id} for bar_id in bar_ids] 

query = """
SELECT * FROM foo_table WHERE bar_id IN :bar_ids
"""
async with db() as db:
    query_result = await db.fetch_all(query, bar_ids)
```

Does encode databases support passing a list of parameters in the IN clause?

**Comment by tomchristie** [comment]
I think you'd need to start out by having more of a dig into this yourself first, try to narrow down exactly what the current behavior is, and what you'd expect it to be.

If those two don't match up then file an issue explaining what the current behaviour is, and what you think it should be instead. Ideally have a look at what query is currently being generated, and see if you can figure out what'd need to change if there is anything wrong there.

**Comment by mazimi** [comment]
This should work:

```
# Input list of bar_ids
bar_ids_input = [1, 2, 3, 4]

query = """
SELECT * FROM foo_table WHERE bar_id = ANY(:bar_ids ::INT[]);
"""
async with db() as db:
    query_result = await db.fetch_all(query, {"bar_ids": bar_ids_input})
```
