### ISSUE TITLE
Database URL parsing seems to have bug.

### ISSUE THREAD

**Issue by shivshankardayal** [encode/databases#175]
Consider this database URL `mysql+pymysql://user:password#@localhost:3306/db_name`. The important part is `#` in the password. Without `#` is works fine but with `#` it starts treating pasword as port number. I see that the problem is with urllib's `urlsplit` function. For example I am pasting output of two different runs:

```
>>>urlsplit("mysql+pymysql://username:password#@localhost:3306/db_name")
SplitResult(scheme='mysql+pymysql', netloc='username:password', path='', query='', fragment='@localhost:3306/db_name')
>>>urlsplit("mysql+pymysql://username:password@localhost:3306/db_name")
SplitResult(scheme='mysql+pymysql', netloc='username:password@localhost:3306', path='/db_name', query='', fragment='')
```

I understand that `#` acts as anchor in URLs and that is why this has come. However, passwords can contain `#` so it does not seem like a good idea to use urlsplit for db connection string parsing.

**Comment by florimondmanca** [comment]
Hi @shivshankardayal!

`#` is a special character for delimiting the [fragment](https://en.wikipedia.org/wiki/Fragment_identifier) in URIs. If your username/passwords can contain special characters you should escape them. This can be done with urllib's `quote` helper:

```python
>>> from urllib.parse import quote, urlsplit
>>> password = 'password#'
>>> url = f'mysql+pymysql://username:{quote(password)}@localhost:3306/db_name'
>>> urlsplit(url)
SplitResult(scheme='mysql+pymysql', netloc='username:password%23@localhost:3306', path='/db_name', query='', fragment='')
```

More info: [Writing a connection string when password contains special characters](https://stackoverflow.com/questions/1423804/writing-a-connection-string-when-password-contains-special-characters)

**Comment by tomchristie** [comment]
Thanks @florimondmanca!
