### ISSUE TITLE
Add 'postgres' as a supported scheme

### ISSUE THREAD

**Issue by usernein** [encode/databases#177]
I'm using Heroku and when i tried to create a Database object using the environment variable DATABASE_URL i got a KeyError because the scheme of DATABASE_URL is 'postgres', not 'postgresql' as written in the source code
https://github.com/encode/databases/blob/98cc2bb0343ca479a69125c771d515ced722713c/databases/core.py#L44

I can just replace the scheme, but it would be nice futurely for new users to just follow the examples (as i tried to) without stopping for understanding the error

**Comment by usernein** [comment]
I just replaced the scheme from 'postgres' to 'postgresql' and now i get AssertionError from this line:
https://github.com/encode/databases/blob/98cc2bb0343ca479a69125c771d515ced722713c/databases/backends/postgres.py#L132

**Comment by gvbgduh** [comment]
hey @usernein, thanks for bringing this, but it's a duplicate issue.

Issue raised in: #146
Fix already available in: #147

**Comment by usernein** [comment]
Oh, sorry
I even did a fork with the same fix
About the AssertionError, it was occurring because i wasn't calling Database.connect()

Thanks!
