### ISSUE TITLE
sqlite: deferred foreign keys and transactions 

### ISSUE THREAD

**Issue by teucer** [encode/databases#184]
If foreign keys are deferred ("DEFERRABLE INITIALLY DEFERRED"), exceptions are only raised at commit time unlike the other [constraints](https://www.sqlite.org/conflict.html).

Exceptions at commit time need to be handled, e.g. for `databases.core.Transaction`:

```python
async def __aexit__(
    self,
    exc_type: typing.Type[BaseException] = None,
    exc_value: BaseException = None,
    traceback: TracebackType = None,
) -> None:
    """
    Called when exiting `async with database.transaction()`
    """
    if exc_type is not None or self._force_rollback:
        await self.rollback()
    else:
        try:
            await self.commit()
        except BaseException:
            await self._transaction.rollback()
            await self._connection.__aexit__()
            raise
```

**Comment by tomchristie** [comment]
I'm not quite clear from this what specific changes you're asking for here. 

If there's any proposal to change something it would also be helpful to look at what other frameworks do here. Eg. In particular what transaction mode does Django uses for sqlite, does it allow it to be customised, and what exception handling implications does it have.
