### ISSUE TITLE
If I use this code,how times will connect to database?

### ISSUE THREAD

**Issue by Chise1** [encode/databases#185]
`query=User.__table__.select().offset(page).limit(per_page)  

paginate_obj=await AdminDatabase().database.fetch_all(query)
query2=select([func.count(User.__table__.c.id)])
total_page=await AdminDatabase().database.fetch_one(query2)
return {"total_page":total_page,
            "list":paginate_obj
            }`

**Comment by tomchristie** [comment]
Hi there, thanks for getting involved. 😃

The best places to start with general usage questions like this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
