### ISSUE TITLE
Support nosql databases

### ISSUE THREAD

**Issue by nikordaris** [encode/databases#186]
Right now core is coupled with sqlalchemy and expects an SQL database for the backend. This prevents the ability to implement a non-sql DB backend. What I propose is to move the [_build_query](https://github.com/encode/databases/blob/master/databases/core.py#L275) out of core and into a SQL DB layer that can wrap existing sql backend implementations this would make core truly agnostic to the backend and enable support for nosql backends. 

FWIW, my company would like to use this database abstraction to implement a neo4j backend so we can standardize on our API for our sql and neo4j transaction management. I could take a stab at doing this PR if you guys are interested in supporting nosql databases or if you only want this tool to be used for SQL DBs then we can just close this issue.

**Comment by aminalaee** [comment]
I think this will be tightly coupled with sqlalchemy (at least for now). So unfortunately we have to close this.
