### ISSUE TITLE
mysql returns rowproxy that is empty but not false

### ISSUE THREAD

**Issue by sloev** [encode/databases#187]
i have the following:

```
 query = """
        SELECT
            SUM(delivered) as delivered
        FROM data
        WHERE
            business_unit_id = :business_unit_id
            AND day >= :from_date AND day < :to_date
        """

    last_period_result = await database.fetch_one(
        query=query,
        values=dict(
            business_unit_id=business_unit_id,
            from_date=two_months_ago,
            to_date=one_months_ago,
        ),
    ) or dict(delivered=0)

    return {
        "invitationsSentPrevious28Days": last_period_result.get("delivered") or 0
    }
```

but i get :

```
raise exception\nsqlalchemy.exc.NoSuchColumnError: \"Could not locate column in row for column 'delivered'
```

no matter what i do.

i would think from reading the code that:

1. if there is a result i would get a dictionary like value that contains the declared keys (in this case "delivered"
2. if there is no values i would get a None value
3. no matter the returned object it would be falsy if not containing values and therefore the "or dict(...)" would be invoked

all this guessing basically renders this completely useless to me and i have spend two days refactoring 1000+ lines to debug this *TWICE*

**how do i answer the simple question: is there data or not**
and it seems as well that the fetch_one does not respect my column alias'es 

🤦

**Comment by charterchap** [comment]
I'm not 100% clear on what you're asking, Could you just change your query to default to 0. `COALESCE(sum(delivered),0)`

**Comment by tomchristie** [comment]
I'll close this off as a discussion, rather than an "issue", but very much looking forward to GitHub introducing a discussions tab, so we can move things like this into a more open-ended state, and leave the issue tracker for confirmed bugs and planned feature work.
