### ISSUE TITLE
Please include docs and tests directories in the tarball

### ISSUE THREAD

**Issue by p1otr** [encode/databases#197]
Hi,

Thanks for writing databases! I use it at work (after trying several other solutions).

Could you re-add docs/ and tests/ directories to the tarball published on PyPI?
I use this tarball to generate [Debian package](https://packages.debian.org/python3-databases) and I want to ship .md files and run tests during build.

**Comment by tomchristie** [comment]
Thanks. I don't think we'll do that no - it's extra overhead that's unused by the vast vast majority of installs. We're not doing that on any of the other 'encode' projects. If there's a strong enough argument that we ought to be doing so everywhere, and a clear consensus from a majority of other python packages to do so, then I'd be up for considering it, but I don't *think?* that's the case.

**Comment by p1otr** [comment]
I'm talking about tarball only, not about eggs. The one with **sources**
