### ISSUE TITLE
Why require psycopg for databases[postgresql]?

### ISSUE THREAD

**Issue by retnikt** [encode/databases#198]
When installing databases with asyncpg PostgreSQL support using `pip install databases[postgresql]`, `psycopg2-binary` is installed as well. This is [not recommended](https://www.psycopg.org/docs/install.html#binary-install-from-pypi), and seems also unnecessary given that there are no references to it in the code, and asyncpg does not require it. Is there any reason for including it as a dependency or is it just a relic of an older version?

**Comment by fullonic** [comment]
The need of psycopg2 is related with sqlalchemy, which databases depends on. But you are right, it shouldn't be the binary version.

**Comment by tomchristie** [comment]
We could consider removing it entirely. (And the corresponding mysql sync driver too.)

`databases` itself *doesn't* require them, but you *do* need them if you want to do `engine.create_all`, or if you want to use `alembic` for database migrations. (In practice you're almost certainly going to want to do one of those.)

I guess a first step here might be - we'll accept a pull request switching it to the non-binary version, and we can follow up if there's any problems with that.

**Comment by jpic** [comment]
Not sure if this helps, but async create_all is in SQLA 1.4b1:

```
with engine.begin() as conn:         
    await conn.run_sync(metadata.create_all)
```

Maybe that'll also be an option.
