### ISSUE TITLE
databases uses aiomysql which has last release in 2018

### ISSUE THREAD

**Issue by sloev** [encode/databases#216]
as stated in aiomysql the maintainer got a new job and is busy, aka dont expect new release soon:
https://github.com/aio-libs/aiomysql/issues/466#issuecomment-640512876

... so: that means the dependency on pymysql is as well falling behind as `aiomysql - install_requires = ['PyMySQL>=0.9,<=0.9.3']`

it also means that libraries like `databases` that try to combine different things under a common interface shields the enduser from the knowledge that they are using oooold un maintained and potentially dangerous code, cuz `databases` is freshly maintained "so i guess all dependencies must be too?" 

i've raised the issue with the maintainer of aiomysql but others have as well **for the last 1.something years**  so i dont expect new releases anymore

**Comment by tomchristie** [comment]
Okay, not really anything I can do about that.

PRs with alternate backend implementations are welcome, maintainers stepping into `aiomysql` are welcome, etc. etc.
