### ISSUE TITLE
Multiple statements in one roundtrip

### ISSUE THREAD

**Issue by olirice** [encode/databases#219]
Is there any way to execute multiple statements in a single roundtrip?

The `execute_*` and `fetch_*` all build a single prepared statement which prevents multiple statements in a single SQL string.

For example, lets say we wanted to set a few local variables before executing a query (common use case for row-level security)

```python
import asyncio
from databases import Database

db = Database('postgresql://...')
await db.connect()

result = await db.fetch_one(query="select 1")
# Returns 1 

await db.fetch_one(query="""
    SET LOCAL jwt.claim.role to 'app_admin';
    SHOW jwt.claim.role;
""") 
# Exception: Cannot insert multiple commands into a prepared statement
```

The example is pretty niche but I think it applies generally for transactions.

```python
async with db.transaction():

    # we don't actually need to flush this and wait for acknowledgement
    # we only care that it executes before the query statement
    await db.execute("SET LOCAL jwt.claim.role to 'app_admin';")

    result = await db.fetch_one(query="SHOW jwt.claim.role")

print(result._row)
```

**Comment by vmarkovtsev** [comment]
Hi @olirice This is not possible to my knowledge. [As you see in the code](https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L160), there is no magic: `databases` delegates all the work to the underlying backend. So if `asyncpg` does not support this, so doesn't `databases`.

Try to hack `asyncpg` directly. If you find a way, we could discuss how to bubble it up here, though I am quite skeptical.

**Comment by olirice** [comment]
Per closed issue on asyncpg ^

This is not currently possible
