### ISSUE TITLE
Any plans integrating Clickhouse backend ?

### ISSUE THREAD

**Issue by matthieugouel** [encode/databases#223]
Hello ! First of all, thanks for your work.

I was wondering if you were planning to add [Clickhouse](https://clickhouse.tech/) database on your backend list ?

I think it could be done using [this](https://github.com/mymarilyn/aioch) async driver as well as [this](https://github.com/cloudflare/sqlalchemy-clickhouse) or [that](https://github.com/xzkostyan/clickhouse-sqlalchemy) Clickhouse dialect for SQLAlchemy. 

Have a good day,
Matthieu.

**Comment by rafalp** [comment]
Hi!

From my understanding, the current plan is to stick to having PostgreSQL/MySQL/SQLite backends by default and [
leave other backends up to the community to maintain and release](https://github.com/encode/databases/pull/151#issuecomment-621115646), however currently there's [no official path for 3rd party backends implementation].

**Comment by matthieugouel** [comment]
Ok, thanks for the quick response.

**Comment by vmarkovtsev** [comment]
I have got an initial clickhouse integration with databases, but I've recently lost it :smile: I'll recover it next week.
