### ISSUE TITLE
Doc error over transaction syntax

### ISSUE THREAD

**Issue by hongyuan1306** [encode/databases#224]
In the doc section over transaction, for a lower-level transaction API, the following example is given:

```
transaction = await database.transaction()
try:
    ...
except:
    transaction.rollback()
else:
    transaction.commit()
```

Actually the `rollback` and `commit` are all async methods. So they shall be all awaited.

**Comment by pumpkiny9120** [comment]
Hi @hongyuan1306 , I also noticed the same after trying the transactions from the documentation. Did it work for you after adding `await`? For some reason it's still auto-committing for me, and I don't know how to turn auto-commit off...

**Comment by hongyuan1306** [comment]
@pumpkiny9120 Yes, it works with the postgresql backend

**Comment by YoshihikoFuruhashi** [comment]
This example code seems to have been changed. 
[transactions](https://www.encode.io/databases/connections_and_transactions/#transactions)
```
transaction = await database.transaction()
try:
    await transaction.start()
    ...
except:
    await transaction.rollback()
else:
    await transaction.commit()
```

And, this is discussed issue #290
