### ISSUE TITLE
Alembic with databses autogenerate empty migration file

### ISSUE THREAD

**Issue by Lepiloff** [encode/databases#228]
I'm trying to connect the `alembic` library to the databases and `sqlalchemy` libraries at fastapi app. As a guide, I use this example  [link][2]

My projects file:

**db.py**

    from databases import Database
    from sqlalchemy import MetaData, create_engine
    
    DATABASE_URL = "postgresql://....@localhost:5432/db"
    
    engine = create_engine(DATABASE_URL)
    metadata = MetaData()
    
    database = Database(DATABASE_URL)

**models.py**

    from sqlalchemy import Table, Column, Integer, String, DateTime
    from sqlalchemy.sql import func
    
    from db import metadata
    
    notes = Table(
        "notes",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("title", String(50)),
        Column("description", String(50)),
        Column("created_date", DateTime, default=func.now(), nullable=False),
    )

**env.py** (alembic settings)

    from db import DATABASE_URL, metadata
    
    ....
    #add new
    target_metadata = metadata
    ...
    #change
    def run_migrations_online():
    
        config.set_main_option('sqlalchemy.url', str(DATABASE_URL))
        connectable = engine_from_config(
            config.get_section(config.config_ini_section),
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )

When I run 

    alembic revision --autogenerate -m 'Add notest table'

the new file at migrations/versions this context is created

    def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###
    
    
    def downgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###

I suppose it may be related to the use of the target_metadata = metadata variable. It seems to be all according to instructions, but the migrations do not work as expected.

  [2]: https://www.starlette.io/database/

**Comment by ajmar3** [comment]
Did you get a solution to this?

**Comment by Lepiloff** [comment]
https://stackoverflow.com/questions/62918026/alembic-autogenerate-empty-migration-file/62919946#62919946
