### ISSUE TITLE
Migrate away from aiomysql

### ISSUE THREAD

**Issue by fabaff** [encode/databases#244]
`aiomysql` is outdated. The last release is almost 2 years old and there is no support for newer PyMySQL release like 0.10.1 which is the latest one.

There is not ETA for a new release (https://github.com/aio-libs/aiomysql/issues/466) or support for PyMySQL > 0.10.

`aiomysql` is a dependency of `databases` and `databases` is dependency of various web framework for DB support. In the current situation all those web frameworks don't have MySQL support on Fedora (Fedora ships  PyMySQL 0.10) and likely other distributions when installed with the distribution-provided packages.

It would be highly appreciated if you consider to migrate to MySQl binding which are actively maintained.

Thanks

**Comment by pquentin** [comment]
@fabaff Do you have a maintained MySQL binding in mind?

**Comment by mrsakkaro** [comment]
looks like new release of aiomysql came out Nov. 28. 2020. It's first release in 2+ years but at least we got one.

**Comment by fabaff** [comment]
This doesn't help as it's just "a release". #518 was not addressed, thus we are getting nowhere unfortunately.

**Comment by synodriver** [comment]
> The only active async mysql driver I found is [asyncmy](https://github.com/long2ice/asyncmy) which has a compatible API with `aiomysql`.
> I'll give this a try.

Could we just replace ```aiomysql``` with ```asyncmy``` because it is said that they are API compatible?

**Comment by aminalaee** [comment]
@synodriver  Yeah. If that's true, that should probably work out of the box.

**Comment by aminalaee** [comment]
I've started a PR for `asyncmy` driver. It's still a work in progress but feel free to give some feedback.

**Comment by synodriver** [comment]
That's great! Thanks for your effort.
