### ISSUE TITLE
Are new releases coming soon?

### ISSUE THREAD

**Issue by Dozer74** [encode/databases#254]
Hey, I've noticed that the last release was made on April 30. The project's growing fast and many important features have been added since then. E.g. [this PR](https://github.com/encode/databases/pull/193) speeds up data fetching by up to 10 times on queries with a large number of results, but the most recent release still does not include it.

Are there any plans on rolling out new versions of the library?

**Comment by vmarkovtsev** [comment]
@tomchristie @encode/maintainers  I would be happy to make a pypi release if somebody gives me the credentials. Besides, it seems like I've been the only responding maintainer of this project recently, so I need the GitHub permissions to merge my own PRs without review.

**Comment by euri10** [comment]
If it's like other encode projects I don't think there's a special permission to have, just hit Release, fill everything, and the publish script should deal with pypi

**Comment by rafalp** [comment]
There's publish action configured in the pipeline, so this should be doable without need for pypi credentials:

https://github.com/encode/databases/blob/master/.github/workflows/publish.yml

**Comment by tomchristie** [comment]
Yup, so if someone issues a pull request simply bumping the version number (and perhaps adding a CHANGELOG too?) then I'll help walk any maintainer through the process of creating a release in GitHub. (Which will then automatically deploy)

**Comment by vmarkovtsev** [comment]
OK, got it, thanks! I will do this through the weekend :+1:

**Comment by vmarkovtsev** [comment]
https://github.com/encode/databases/pull/255

**Comment by vmarkovtsev** [comment]
Hurray! I created a new tag and the automation did the rest indeed.
