### ISSUE TITLE
How to set PostgreSQL transaction level?

### ISSUE THREAD

**Issue by estan** [encode/databases#258]
Sorry if this is not the place for questions, but how can I control the PostgreSQL isolation level? I.e. the `isolation_level` argument you normally pass to SQLAlchemy's `create_engine` function.

**Comment by estan** [comment]
I found that I can e.g. decorate with `@database.transaction(isolation="repeatable_read")`, but still interested in if it's possible to set the default (i.e. what passing `isolation_level` to `create_engine` would do).

**Comment by vsokoltsov** [comment]
@estan Hello!

Does the decorator option really works?
Tried with context manager (`with database.transaction(isolation='repeatable_read')`), and it seems, that the backend (`asyncg`) does not receive isolation option

**Comment by estan** [comment]
@vsokoltsov I'm not sure I ever verified that it works, but from what I remember, I got some errors if I passed in something else than "repeatable_read", e.g. "foobar", so I think I just assumed that it was working.

I can double-check, but it'll take a while since I'm a bit held up with other things. Would be nice if some `databases` dev could confirm that this should work.

What is the errors you got BTW?

**Comment by estan** [comment]
BTW I'm not sure I ever tried the context manager, I think I only used the decorator. Don't know if that makes a difference though.

**Comment by vsokoltsov** [comment]
I received `apg_errors.InterfaceError`, just like it is mentioned in the [doc](https://magicstack.github.io/asyncpg/current/_modules/asyncpg/transaction.html)

It seems that `isolation` parameter for context manager works as well.

**Comment by estan** [comment]
Coming back to this again in our application. We would really like to be able to set the default transaction isolation level (i.e. the equivalent of the `isolation_level` parameter in SQLAlchemy's `create_engine`). Do you know if it's possible or not @tomchristie ?

**Comment by estan** [comment]
Ah, nevermind, I found out now that extra kwargs passed to `Database` are passed on all the way down to the asyncpg `Connection`, which takes a `server_settings` dict param.

So I can pass `server_settings={"default_transaction_isolation": "repeatable read"}` to `Database` and it'll work.

@tomchristie You can close this issue I think :+1:
