### ISSUE TITLE
Name collision in join query.

### ISSUE THREAD

**Issue by micheller** [encode/databases#263]
The problem might be seen when one joins two tables (A, B), each one having a column with same name:
```select a.uid, b.uid from a left outer join b on a.uid = b.a_id```

What happens when you try to `fetch_one` this query, given table B has no records at all?
Something like this:
```
assert [(k,v) for k,v in result.items()] == [('uid', None), ('uid', None)]
```
What I'd expect is either an Exception of some kind, or a not-overwritten value, which column's name matches any other column's name.

P.S. happens at least on postgresq, python 3.8, databases 0.4.0

**Comment by vmarkovtsev** [comment]
Hi! `databases` is irrelevant to this pure sqlalchemy question. Try asking that in the community resources instead.

There is also [`alias`](https://www.tutorialspoint.com/sqlalchemy/sqlalchemy_core_using_aliases.htm#:~:text=The%20alias%20in%20SQL%20corresponds,referenced%20by%20a%20unique%20 name).
