### ISSUE TITLE
UPDATE query returns none

### ISSUE THREAD

**Issue by abhijitgujar86** [encode/databases#271]
I am using raw SQL query to update the table 

rows = await app.db.execute( query= query )

the rows in none  

1 ) How will i know if the query is successful or not 
2) how will i know that how many rows have been updated ?

**Comment by henriqueblang** [comment]
Not sure if this is the best approach, but maybe you could add a `RETURNING` clause in your SQL query and call a fetch variation instead of `execute`.
If your query is unsuccessful, your result will be `None`; else, you'll be able to find out how many rows were affected.

**Comment by T-rain** [comment]
Using `RETURNING` will be helpful. Test with postgresql.

```python
import databases
from sqlalchemy import update

database = databases.Database(DATABASE_URL)

update_stmt = update(
    user_table
).where(
    user_table.c.name == 'patrick'
).values(
    fullname='Patrick the Star'
).returning(
    user_table.c.id, user_table.c.name, user_table.c.fullname
)

record_list = await database.fetch_all(update_stmt)
return record_list
"""
if success:
record_list = [{ "id": XXX, "name": "patrick", "fullname": "Patrick the Star" }]

name == 'patrick' not found, no update:
record_list = []
"""
```

Ref: 
1. https://docs.sqlalchemy.org/en/14/tutorial/data_update.html#using-returning-with-update-delete
2. https://github.com/encode/databases/issues/55
3. https://github.com/encode/databases/issues/98
