### ISSUE TITLE
Postgres fetch_all() with SQLAlchemy returns object list instead of data

### ISSUE THREAD

**Issue by NAVHITS** [encode/databases#277]
I tried to do `fetch_all()` to list all records. However it returns a list of objects like this. I use this with FastAPI.

```
[<databases.backends.postgres.Record object at 0x1067f9860>, <databases.backends.postgres.Record object at 0x1067f98b0>, <databases.backends.postgres.Record object at 0x1067f9ae0>]
```

I am not sure on how to read the record object yet. For other CRUD operations I did not face such issues. When I pass the object to a Pydantic model, it serializes the data. However I'm stuck here. Any help appreciated.

Here's a minimum version of the code to see what I have done.

```py

db = Database(DATABASE_URL)
metadata = sqlalchemy.MetaData()

metrics = sqlalchemy.Table(
    "metrics",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column("status", sqlalchemy.Enum(WorkflowStatus), default=WorkflowStatus.UNKNOWN),
    sqlalchemy.Column("startTime", sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column("endTime", sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column("elapsedTime", sqlalchemy.Numeric(precision=10), default=0.0),
    sqlalchemy.Column("metaData", sqlalchemy.dialects.postgresql.JSON)
)

class Metrics:
    @classmethod
    async def get_all(cls):
        query = metrics.select()
        return await db.fetch_all(query=query)

# Below is a from FastAPI's api view
async def get_all_data():
    info = await Metrics.get_all()

```

System info
```
Platform: Mac OS 
Python version: 3.9
Databases version: 0.4.0
FastAPI version: 0.61.2
Psycopg2 version: 2.8.6
SQLAlchemy version: 1.3.20
Postgres version = 13.0
```

**Comment by NAVHITS** [comment]
Update:
I iterated over the objects and used Pydantic to deseralize and now it seems to be fine.

Sample code
```py
deseralized_data = [MetricSchema(**datum).dict() for datum in data]
```

**Comment by evseevnn** [comment]
@NAVHITS What about using join in query? how we can map results in this case?

**Comment by xyz2022** [comment]
> I tried to do fetch_all() to list all records. However it returns a list of objects 

It turns out you can replace db.fetch_all(query=query) with db.execute(query=query)

Execute returns a list of ids not data objects
