### ISSUE TITLE
ssl mode only true or false?

### ISSUE THREAD

**Issue by devidkarundeng** [encode/databases#278]
Hi, trying to connect to managed db in digitalocean, which has ssl=require and ca_certificate by default. Looks like encode/databases only support ssl true of false? Any advice?

**Comment by julian-r** [comment]
there is an alternative: you can connect via a kwarg while creating the connection:

```py
db = databases.Database("postgresql://..../", ssl="require")
```

**Comment by devidkarundeng** [comment]
@julian-r Thanks! it works!
