### ISSUE TITLE
Question: Different types of Results depending on database? (Postgres/Sqlite)

### ISSUE THREAD

**Issue by Sharleedah** [encode/databases#279]
Hello,

when using a sqlite-db i will get a response with the type "sqlalchemy.engine.result.RowProxy" in case of a postgres i get "databases.backends.postgres.Record". Is there a way to get the same types in both cases? (eg sqlalchemy.engine.result.RowProxy)

BR

**Comment by aminalaee** [comment]
@Sharleedah 
I don't know your use case, but the returned row has a mapping interface you can use:

```python
...
query = notes.select()
row = await database.fetch_one(query=query)
```

Here it doesn't matter which backend you use, you can use the mapping interface which can be turned into a dictionary:
```python
dict(row._mapping)
```
