### ISSUE TITLE
Any support return dict from fetch?

### ISSUE THREAD

**Issue by abersheeran** [encode/databases#285]
In many synchronous IO libraries, cursor.fetch_all() is allowed to return a sequence of dictionaries. Do databases consider similar implementations?

Just like:

```python
rows: List[Dict[str, Any]] = await database.fetch_all(query=query, include_field_name=True)
```

**Comment by vmarkovtsev** [comment]
Sorry, this would be too much of a breaking change. It returns native DB records which inherit from `Mapping`, so that `dict(row)` and `row["column"]` work.
