### ISSUE TITLE
mysql connection string problem

### ISSUE THREAD

**Issue by yoandinkov** [encode/databases#289]
Hi all,

Trying to do a simple connection to a mysql db, by I cannot seem to use the right `url` so wanted to ask if somebody, can share a working example for mysql url.

Currently I am using ["a default orm"](https://stackoverflow.com/questions/372885/how-do-i-connect-to-a-mysql-database-in-python) url as follows:
```python3
 return "mysql://{}:{}@{}/{}".format(
            values['mysql_user'],
            values['mysql_pass'],
            values['mysql_host'],
            values['mysql_db']
        )
```

I am getting following error
```
ValueError: Port could not be cast to integer value as 'w'
````

**_I don't provide any port (in `mysql_host` for example) as I depend on default port convention 3306._**

I've tried as well with [jdbc style](https://stackoverflow.com/questions/8380909/connect-to-a-database-url-in-python-where-the-url-is-for-jdbc)
```python3
return "mysql://{}/{}?user={}&password={}".format(
            values['mysql_host'],
            values['mysql_db'],
            values['mysql_user'],
            values['mysql_pass']
        )
```
Yet the second format gets a step further, but still cannot recognize my user and password.

So I am currently stuck. I do have one special symbol in my password - `?`, yet not sure if this is the problem, and if so how to encode it properly.

From my perspective, it looks like that there is way better support for Postgres, but because of historical reasons, I am stuck with MySQL for the moment.

Any suggestions for how should I structure my mysql connection string / url and how should encode my password?

**Comment by STeveShary** [comment]
@yoandinkov You need to make sure that you convert special characters.  Here is an example: https://stackoverflow.com/a/68268537

**Comment by aminalaee** [comment]
https://github.com/encode/databases/issues/404
