### ISSUE TITLE
Transactions error

### ISSUE THREAD

**Issue by jiangshujsf** [encode/databases#290]
https://www.encode.io/databases/connections_and_transactions/
For a lower-level transaction API:

```
transaction = await database.transaction()
try:
    await transaction.start()
    ...
except:
    await transaction.rollback()
else:
    await transaction.commit()
```

it's unable work nomaly

but in https://www.starlette.io/database/
After reomve 'await transaction.start()',it's working

**Comment by adiferd** [comment]
Also happen on my case @jiangshujsf 

using 
```
databases==0.2.6
Python 3.8.7
```

rollback and commit works after removing  
`await transaction.start()`

**Comment by mrsakkaro** [comment]
I also can confirm that rollback and commit works fine after removing `await transaction.start()`

**Comment by aminalaee** [comment]
I can reproduce this with `databases==0.5.1`, `python3.8` and `postgresql`.
If this still exists please create another issue.
