### ISSUE TITLE
Full integration examples

### ISSUE THREAD

**Issue by tomchristie** [encode/databases#31]
We'll want integration examples with a few frameworks.
Certainly at least Starlette and Sanic.
Perhaps also aiohttp and Responder.

**Comment by foxmask** [comment]
will be great if we could have an example of abstract data access for example:

instead of 

app.py
```
import databases
import sqlalchemy
from starlette.applications import Starlette
from starlette.config import Config
from starlette.responses import JSONResponse


# Configuration from environment variables or '.env' file.
config = Config('.env')
DATABASE_URL = config('DATABASE_URL')


# Database table definitions.
metadata = sqlalchemy.MetaData()

notes = sqlalchemy.Table(
    "notes",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column("text", sqlalchemy.String),
    sqlalchemy.Column("completed", sqlalchemy.Boolean),
)

# Main application code.
database = databases.Database(DATABASE_URL)
app = Starlette()


@app.on_event("startup")
async def startup():
    await database.connect()


@app.on_event("shutdown")
async def shutdown():
    await database.disconnect()


@app.route("/notes", methods=["GET"])
async def list_notes(request):
    query = notes.select()
    results = await database.fetch_all(query)
    content = [
        {
            "text": result["text"],
            "completed": result["completed"]
        }
        for result in results
    ]
    return JSONResponse(content)
```

something like this, spliting this in 3 like this:

models.py
```
notes = sqlalchemy.Table(
    "notes",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column("text", sqlalchemy.String),
    sqlalchemy.Column("completed", sqlalchemy.Boolean),
)
```

datasource.py
```
from models import notes

class DataSource:

    async def list_notes(self):
        query = notes.select()
        return await database.fetch_all(query)
```
app.py
```
from datasource import DataSource

@app.route("/notes", methods=["GET"])
async def list_notes(request):
    data = DataSource.list_notes()
    content = [
        {
            "text": result["text"],
            "completed": result["completed"]
        }
        for result in data
    ]

    return JSONResponse(content)
```
if it's possible, I do not see yet how to pass `metadata` instance from the ` app.py`  to the `models` class

**Comment by tomchristie** [comment]
>  I do not see yet how to pass metadata instance from the app.py to the models class.
thus we are able to abstract the data provider

In this example just put `metadata = sqlalchemy.MetaData()` in your `models.py` module in the first place - it doesn't need to be in `app.py`. (Tho I'd probably call it `tables.py` instead.)

**Comment by skewty** [comment]
Regarding `class DataSource` above:
- Perhaps `@singleton` or using `@staticmethod` makes more sense?  
- My IDE (PyCharm) will rightfully complain about methods that have `self` and don't use it.

The documentation example should also have a bit of Alembic integration (for migrations) illustrated as well IMO.  Most production sites will eventually run up against db migrations and being able to leverage Alembic is a big advantage to this module IMO.

I have been looking at ways to implement a similar structure as above but with more control over coupling and avoiding the long class code smell.  In a larger site `class DataSource` would have many methods and most methods that couple it wouldn't need most of what the class offers.   Perhaps separate `class DataSource` into groupings based on how the class is actually used?

```py
class FooOps:
    @staticmethod
    def method_a(pk: int): ...

    @staticmethod
    def method_b(pk: int, a: str): ...


class BarOps:
    @staticmethod
    def method_x(pk: int): ...

    @staticmethod
    def method_y(pk: int, a: str): ...
```

Thoughts / suggestions / comments?

**Comment by tomchristie** [comment]
Closing this now as I think it's actually out of scope.
