### ISSUE TITLE
disconnect does not really disconnect

### ISSUE THREAD

**Issue by shivshankardayal** [encode/databases#342]
I am using databases with FastAPI. I need to connect and disconnect for every request. Every time I invoke an API call no. of connections increase while I ensure that I disconnect in code. It seems diconnect is not really working. It also spawns lots of socat and pause processes. Quite curiously, if I leave postgres idle for sometime these connections get closed automatically.

**Comment by rafalp** [comment]
Can you say which database driver are you using?

Potentially related to #340

**Comment by shivshankardayal** [comment]
I am using psycopg2.

**Comment by shivshankardayal** [comment]
I observed that for every connection asyncpg pool created 10 connections. Also, after 5 minutes these are closed back as idle connections.

**Comment by shivshankardayal** [comment]
Please ignore this. Library is working fine, My code had bug where I missed one branch for disconnect from database.
