### ISSUE TITLE
select pg_advisory_unlock_all() called every time and it's slow

### ISSUE THREAD

**Issue by tigrus** [encode/databases#344]
We have following issue: 

```
db_1  | 2021-05-31 19:16:37.306 UTC [152] LOG:  statement: BEGIN;
db_1  | 2021-05-31 19:16:37.312 UTC [152] LOG:  execute __asyncpg_stmt_1__: INSERT INTO clinic .....
db_1  | 2021-05-31 19:16:37.335 UTC [152] LOG:  execute __asyncpg_stmt_2__: INSERT INTO address ......
db_1  | 2021-05-31 19:16:37.352 UTC [152] LOG:  execute __asyncpg_stmt_3__: INSERT INTO purpose ......
db_1  | 2021-05-31 19:16:37.362 UTC [152] LOG:  statement: COMMIT;
db_1  | 2021-05-31 19:16:37.365 UTC [152] LOG:  statement: SELECT pg_advisory_unlock_all();
db_1  |         CLOSE ALL;
db_1  |         UNLISTEN *;
db_1  |         RESET ALL;
db_1  | 2021-05-31 19:16:47.401 UTC [152] LOG:  statement: BEGIN;
```

For some reason pg_advisory_unlock_all called every time and takes 10 seconds. On clean test database. 

How it's used and what we can do about it? Can it be disabled for tests somehow? 

I haven't found direct calls of it in encode/databases btw...

**Comment by vmarkovtsev** [comment]
Hi @tigrus. databases is a thin wrapper around asyncpg and does not do anything outstanding. You should ask asyncpg developers directly.
Please feel free to ping here if they blame databases.
