### ISSUE TITLE
postgresql+aiopg - giving error sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.aiopg

### ISSUE THREAD

**Issue by jaytimbadia** [encode/databases#360]
Giving Error

SQLALCHEMY_DATABASE_URI = (
    "postgresql+aiopg://{}:{}@{}:{}/{}"
)

username = 'postgres'
password = 'password'
hostname = 'localhost'
port = '5432'
db_name = 'postgres'

metadata = MetaData()

databaseurl = DatabaseURL(SQLALCHEMY_DATABASE_URI.format(username, password, hostname, port, db_name))
database = Database(databaseurl, force_rollback=True)

Error ; sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.aiopg

You also have a lot of version issues. Is this project still active.
Please let me know what is the solution to use proper asynchronous postgres with engine and session and executing raw SQL not ORM queries.

Thanks.

**Comment by VitalyPetrov** [comment]
Hi

It looks like you have an outdated version of SQLAlchemy, which does not support async I/O syntax.
Try up the version of SQLAlchemy to 1.4.* which natively supports it.
Or you can switch the pg driver to [asyncpg](https://github.com/MagicStack/asyncpg)

Hope that helps

**Comment by aminalaee** [comment]
@jaytimbadia Please create a new issue or provide more info for this.
