### ISSUE TITLE
SQLAChemy 1.4 POSTCOMPILE error

### ISSUE THREAD

**Issue by mrchoke** [encode/databases#377]
I try new encode/databases and  SQLAChemy 1.4 everything  work fine, except

```
sql = select([TABLE]).where(TABLE.c.id.in_([1,3,4]))
print(databases.fetch_all(sql))
```

it produced  error

```
psycopg2.errors.SyntaxError: syntax error at or near "["
LINE 3: WHERE TABLE.id IN ([POSTCOMPILE_1])
```

But I can use this query with pure SQLAChemy 1.4 core

```
sql = select([TABLE]).where(TABLE.c.id.in_([1,3,4]))
async with engine.connect() as conn:
      res = await conn.execute(sql)
print(res.fetchall())
```

**Comment by aminalaee** [comment]
@mrchoke Thanks for reporting this.
You're right, this was changed in sqlalchemy 1.4 [here](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#all-in-expressions-render-parameters-for-each-value-in-the-list-on-the-fly-e-g-expanding-parameters)
