### ISSUE TITLE
Install problems with poetry

### ISSUE THREAD

**Issue by FZetting** [encode/databases#384]
Hello,

when i try to install databases with version 0.5.* i got the error:

  AttributeError

  'EmptyConstraint' object has no attribute 'allows'

  at c:\program files\python38\lib\site-packages\poetry\core\version\markers.py:291 in validate
      287│
      288│         if self._name not in environment:
      289│             return True
      290│
    → 291│         return self._constraint.allows(self._parser(environment[self._name]))
      292│
      293│     def without_extras(self):  # type: () -> MarkerTypes
      294│         return self.exclude("extra")
      295│

The command line was: poetry add databases@0.5.0

If i change the version to 0.4.3 everythng works as expected.

Regards
Franz

**Comment by aminalaee** [comment]
@FZetting Can you check what version of poetry you have?

I just tried that, and according to [this](https://github.com/python-poetry/poetry/issues/4410) upgrading `poetry self update` solves this issue.

**Comment by aminalaee** [comment]
I believe this fixes the issue, please leave comment if it still exists.
