### ISSUE TITLE
IndexError is displayed after `force_rollback=True` is set.

### ISSUE THREAD

**Issue by tufbel** [encode/databases#387]
When I test with Pytest, I expect the database to roll back when the test is done.
My initial code was "databases.Database(DATABASE_URL)", and all my tests passed.
There was an error when I changed it to "databases.Database(DATABASE_URL, force_rollback=True)":
```
    async def rollback(self) -> None:
        async with self._connection._transaction_lock:
>           assert self._connection._transaction_stack[-1] is self
E           IndexError: list index out of range

...\site-packages\databases\core.py:379: IndexError
```

**Comment by aminalaee** [comment]
@tufbel Can you share a sample code causing this?
