### ISSUE TITLE
IndexError is displayed after `force_rollback=True` is set.

### ISSUE THREAD

**Issue by tufbel** [encode/databases#388]
When I test with Pytest, I expect the database to roll back when the test is done.
My initial code was `databases.Database(DATABASE_URL)`, and all my tests passed.
There was an error when I changed it to `databases.Database(DATABASE_URL, force_rollback=True)`:
```
    async def rollback(self) -> None:
        async with self._connection._transaction_lock:
>           assert self._connection._transaction_stack[-1] is self
E           IndexError: list index out of range

...\site-packages\databases\core.py:379: IndexError

**Comment by aminalaee** [comment]
@tufbel Can you share a sample code causing this?

You already opened an Issue for this. Please close one of them.

**Comment by tufbel** [comment]
> @tufbel Can you share a sample code causing this?
> 
> You already opened an Issue for this. Please close one of them.
I use FastAPI:
```
# conftest.py
@pytest.fixture(scope="session")
def event_loop():
    loop = asyncio.get_event_loop()
    yield loop
    loop.close()


@pytest.fixture(scope="session", autouse=True, name="fast_client")
async def start_async_fastapi():
    database_ = app.state.database
    if not database_.is_connected:
        await database_.connect()

    async with AsyncClient(app=app, base_url="http://test") as fast_client:
        yield fast_client

    database_ = app.state.database
    if database_.is_connected:
        await database_.disconnect()


# main.py
app = FastAPI()
app.state.database = database

# database.py
# Pass
database = databases.Database(DATABASE_URL)

# IndexError
databases.Database(DATABASE_URL, force_rollback=True)
```

**Comment by aminalaee** [comment]
@tufbel I tested that on python 3.8 and `databases==0.5.2` and it works fine both with and without `force_rollback` on all databases `sqlite`, `mysql` and `postgresql`.
What versions do you use?

**Comment by tufbel** [comment]
> @tufbel I tested that on python 3.8 and `databases==0.5.2` and it works fine both with and without `force_rollback` on all databases `sqlite`, `mysql` and `postgresql`.
> What versions do you use? Is that error happening in your tests? I wrote a simple test and it's ok.

Ok, I will continue to test and check my code, thank you.
