### ISSUE TITLE
how to use update query

### ISSUE THREAD

**Issue by Curioo** [encode/databases#392]
Hello, Im trying to update a column called queue_embed_id using the UPDATE function. This is what i have:
![image](https://user-images.githubusercontent.com/47332301/133595651-2802f971-9bf3-4646-9446-51e0c1788bd8.png)
I get the following error: 
`    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "$2"`

Why does this not work and how can i fix it?
I look forward to your answers,
Max

**Comment by aminalaee** [comment]
Hi @Curioo ,
Shouldn't the query be something like  this?

```
UPDATE bug_handling SET queue_embed_id=:queue_embed_id WHERE id=:bug_id
```

And data:

```python
values = {"queue_embed_id": "", "bug_id": ""}
```

If you can paste an example, it would be easier to help.

**Comment by aminalaee** [comment]
Please update the issue if you still have questions/problems.
