### ISSUE TITLE
Add support for postgresql+asyncpg DB scheme

### ISSUE THREAD

**Issue by mhadam** [encode/databases#395]
The supported DBs dict is missing this scheme prefix.

https://github.com/encode/databases/blob/6fcb16823c32dbf492991f26562a3ca6884dfbef/databases/core.py#L45

**Comment by aminalaee** [comment]
I think the reason behind this is that we use default database drivers:
`postgresql` --> `asyncpg`
`mysql` --> `aiomysql`
`sqlite` --> `aiosqlite`

Alternatives:
`postgresql+aiopg`
`mysql+asyncmy` (work in progress)

Is that causing any problems?
