### ISSUE TITLE
How to log all of the query sql string with args ?

### ISSUE THREAD

**Issue by insoz** [encode/databases#397]
I tried set `echo=True` and `logging.getLogger("databases").setLevel(logging.DEBUG)`, but both are not working.

Are there have some method to log sql string and args except `print(query)` ? I want something global.

Thank you !

**Comment by aminalaee** [comment]
@insoz
Have you tried this?

```python
import logging
logging.basicConfig()
logging.getLogger('databases').setLevel(logging.DEBUG)
```

**Comment by insoz** [comment]
> @insoz
> Try this:
> 
> ```python
> import logging
> logging.basicConfig()
> logging.getLogger('databases').setLevel(logging.DEBUG)
> ```

It works!
