### ISSUE TITLE
Support for DDL expressions etc.

### ISSUE THREAD

**Issue by tomchristie** [encode/databases#40]
Currently migrations and table creation is always performed using sync drivers.

At some point we might want to consider how we can properly integrate the async drivers all the way through, in order to have low-dependency installs, and in order to make sure we're using the same drivers both for migration operations and for regular interactions.

There's no performance reasons for doing so, but it'd be nice if we had comprehensive support for the full set of possible database operations.

**Comment by pvanliefland** [comment]
Are you thinking about a solution without SQLAlchemy / Alembic?

**Comment by tomchristie** [comment]
Kinda. Eg. right now if test cases are using `engine.create_all()`, `engine.drop_all()` you're having to use a regular syncronous driver. That's fine but it means that we always have two sets of dependencies. An async database driver for the regular code, and a sync database driver for any migrations or table setup. It'd be nice if we didn't need to do that.

**Comment by tomchristie** [comment]
Something like...

```diff
-    async def execute(self, query: ClauseElement) -> typing.Any:
+    async def execute(
+        self, query: typing.Union[ClauseElement, DDLElement]
+    ) -> typing.Any:
         assert self._connection is not None, "Connection is not acquired"
-        query, args, result_columns = self._compile(query)
-        return await self._connection.fetchval(query, *args)
+        if isinstance(query, DDLElement):
+            compiled = query.compile(dialect=self._dialect).string
+            await self._connection.execute(compiled)
+            return
+        else:
+            query, args, result_columns = self._compile(query)
+            return await self._connection.fetchval(query, *args)
```
