### ISSUE TITLE
"Connection is already acquired" error

### ISSUE THREAD

**Issue by bokolob** [encode/databases#405]
Hi. I have a daemon with several asyncio tasks, each of which executes some requests. All of the tasks share the same connection.

After some time one of them begins to produce this error.

Failed code is simple :)

In main.py I have
`self.engine = Database(config.Config.SQLALCHEMY_DATABASE_URI)
 await self.engine.connect()
`

And in broken task
`await wait_for(self.engine.execute(query=statement), 10)
`
What could be wrong?

**Comment by aminalaee** [comment]
I think they don't share the same connection, they run in a connection pool.
It would be great if you could post a sample code to reproduce this.

**Comment by bokolob** [comment]
I would replace release function with the next piece of code:

```
    async def release(self) -> None:
        assert self._connection is not None, "Connection is not acquired"
        assert self._database._pool is not None, "DatabaseBackend is not running"
        self._connection = None
        await self._database._pool.release(self._connection)
```

**Comment by aminalaee** [comment]
@bokolob What version of `databases` do you have?
I'll take another look, but if you feel like this will fix it, feel free to create a PR for it.

**Comment by bokolob** [comment]
I will try to reproduce with your example later. I use real hardware, maybe there is a difference.
