### ISSUE TITLE
Postgres backend Record is a Mapping but some Mapping methods are deprecated

### ISSUE THREAD

**Issue by ugtar** [encode/databases#407]
Since https://github.com/encode/databases/pull/299 upgraded to sqlalchemy 1.4, the postgres backend's Record object now mimics the behavior of sqlalchemy's Row which is meant to behave similarly to a NamedTuple (and inherits from collections.abc.Sequence) https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#change-4710-core

Meanwhile, postgres backend's Record object inherits from collections.abc.Mapping and is therefore required to fulfill the Mapping interface, which includes keys() and values() which are now deprecated.

Sqlalchemy provides a `mapping()` method on Result which will cause it to return RowMapping objects rather than Row objects, and those look like Mappings.

I encountered this issue working with fastapi and pydantic. Returning Records as pydantic models worked in the past, but now produces a deprecation warning (and i guess will eventually stop working) since pydantic's builtin validator treats the Record as a Mapping and attempts to call `dict(record)`

**Comment by aminalaee** [comment]
Sorry I'm a little confused now, I don't know much about Pedantic.
Do you mean that this works in Pydantic?
```python
[r._mapping for r in results]
```

But calling `dict(record)` produces DeprecationWarning?

**Comment by aminalaee** [comment]
@ugtar Yes in that case you are right, `Mapping` should implement `keys()` and `values()`, `items()`, etc but it doesn't.
I don't see the point in keeping that a `Mapping` anymore.
