### ISSUE TITLE
DB_URL not working when DB_USER is `postgres`

### ISSUE THREAD

**Issue by harshitsinghai77** [encode/databases#409]
My 

`DB_URL = "postgresql://postgres:_Ij=de-6S8B$avgXtFN?@U-+0gnAZ0x!@z3baa5944-postgresql.qovery.io:5432/postgres"`

I'm getting 
`ValueError: Port could not be cast to integer value as '_Ij=de-6S8B$avgXtFN'`
Even though it is not a `Port`. It's `DB_PASSWORD`.

Can you please tell what I'm doing wrong?

**Comment by aminalaee** [comment]
@harshitsinghai77 I think it's not related to the Postgres user. It's your password which should be encoded.
Same as this: https://github.com/encode/databases/issues/404

**Comment by harshitsinghai77** [comment]
You can tell me how to encode the password? I'm using it as it's given by Qovery. Initially, I was using Heroku, which was working fine. 

Can you tell me what exactly needs to be done.

**Comment by harshitsinghai77** [comment]
Thanks @aminalaee 

It worked.

Update code
```python
from urllib.parse import quote

ENCODED_PASSWORD = quote(DB_PASSWORD)
DATABASE_URL = f"postgresql://{DB_USER}:{ENCODED_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

database = databases.Database(DATABASE_URL)
```

Thanks again for the help @aminalaee :raised_hands: This was really helpful.
You can close the issue if you want.

**Comment by aminalaee** [comment]
Glad it's resolved.
