### ISSUE TITLE
[HELP] Utilise the COUNT function

### ISSUE THREAD

**Issue by Curioo** [encode/databases#417]
Hello, im trying to use the **COUNT** function to get the amount of times a value pops up in a given table. This is the code i used to fetch the data. How can i access the actual number that the query returns? does it even return one? 
Thanks in advance, 
Max

`send_data = 'select COUNT(userid) from bug_participation where userid = :userid'
    values = {"userid": int(submitter)}
    result = await database.fetch_one(query=send_data, values=values)
    print(result.get('userid'))`

*EDIT: Seems like my code didnt format correctly when i put it here. Here's a screenshot!
![screenshot](https://user-images.githubusercontent.com/47332301/139433693-f9740c76-74cd-4757-a08e-eac9597429f8.png)

**Comment by aminalaee** [comment]
I'll close this one, if you any issues, we'll re-open this.
