### ISSUE TITLE
"SELECT OUTFILE" AND "LOAD INFILE" blocking code

### ISSUE THREAD

**Issue by ghostebony** [encode/databases#420]
```await database.execute(f"SELECT {table}.* INTO OUTFILE '{path}/{table}.tsv' FROM {table}")``` (mysql)
I guess is blocking because there is no response for this query

**Comment by aminalaee** [comment]
Thank you for reporting this.

Can you please provide info about what versions of `databases` and drivers you use?
And also a full failing example would be awesome.

**Comment by ghostebony** [comment]
databases[mysql]>=0.5.3
pymysql>=0.9.3

```py
def backup():
    today = datetime.today().strftime("%d-%m-%Y")
    backup_path = f"{backups_path}/{today}"
    sql_backup_path = str(Path(backup_path).resolve()).replace("\\", "/")
    create_folder(backup_path)
    for table in metadata.tables.keys():
        await database.execute(f"SELECT {table}.* INTO OUTFILE '{sql_backup_path}/{table}.tsv' FROM {table}")
```

**Comment by ghostebony** [comment]
this also blocks the code, has no response from mysql

```py
await database.execute(f"LOAD DATA LOCAL INFILE '{sql_backup_path}/{table}.tsv' INTO TABLE {table}")
```

**Comment by aminalaee** [comment]
@ghostebony Is the issue resolved?

**Comment by ghostebony** [comment]
this was not the issue, I was using fastapi -> background_tasks and that is blocking the code
