### ISSUE TITLE
how to reconnect database

### ISSUE THREAD

**Issue by f4ct0r** [encode/databases#428]
I usually use databases in FastAPI, and I use on_event("startup") to connect the database. But under some circumstances this error occurs: 
```
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')
```
MySQL got disconnect, so I can’t access api. How should I fix it?

**Comment by aminalaee** [comment]
We need a little bit of context here. As why this happening and etc.

But if what you're after is how to reconnect, I think you can just call `.connect()` again, in the latest release it's become idempotent, so you can call it even if you're connected, and it will ignore if you're connected.

**Comment by f4ct0r** [comment]
@aminalaee Thanks for your reply! The reason for this error may be because I used kube-proxy I think. But I don't know why kube-proxy cause this error.
And I found FastAPI can reconnect database automatically. So I think this error can be ignored.
