### ISSUE TITLE
About python 3.5 support

### ISSUE THREAD

**Issue by em92** [encode/databases#44]
Currently I maintain [port](https://github.com/em92/databases) for databases. I think it would be better to add note in readme about python 3.5 support. What do you think about it?

Same about starlette.

**Comment by tomchristie** [comment]
Note sure really. I guess we *might* accept a PR for the docs, but I'm not super keen on it being a particularly prominent thing, since I can't vouch for any backports.

**Comment by em92** [comment]
> I guess we might accept a PR for the docs

Added https://github.com/encode/starlette/pull/413

Currently no PR for databases, 'cos could not the best place to add it.
