### ISSUE TITLE
Missing named access to result set

### ISSUE THREAD

**Issue by bustbr** [encode/databases#445]
Hi,

#408 changed the return type for all fetch ops from `Mapping` to `Sequence`, because of [a change in SQLAlchemy 1.4](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#rowproxy-is-no-longer-a-proxy-is-now-called-row-and-behaves-like-an-enhanced-named-tuple).

This means Databases doesn't seem to offer any standard way to access the result values by name anymore.  
The [postgres backend offers a `_mapping` property](https://github.com/encode/databases/blob/f6b28ad67c01e6d5f9c9d73da424f24fcbcb410f/databases/backends/postgres.py#L107-L109) and all the other backends are using SQLAlchemy's `Row`, which means `_mapping` is also available, but this is not documented as far as I can tell.

In SQLAlchemy the change wasn't intended to remove named access, the returned Row offers the result set as properties instead, like a named tuple, and [in SQLAlchemy 2.0 there's a `mapping()` method](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.mappings) on the result.

Could we add a standardized way of accessing the mapping in Databases as well?
Adding the `_mapping` property to the result set interface would be enough, but maybe there's a better idea.
Another easy way would be to implement `__getattr__` on the [postgres backend's `Record` type](https://github.com/encode/databases/blob/f6b28ad67c01e6d5f9c9d73da424f24fcbcb410f/databases/backends/postgres.py#L81).

**Comment by laukhin** [comment]
+1 it breaks whole database layer for my project. It's really unexpected to have such a drastic interface change from minor release like 0.5.3 -> 0.5.4.

**Comment by laukhin** [comment]
Thank you for the quick response. I've created PR #447 for it, please check it out :)

**Comment by aminalaee** [comment]
As for the named access to the row result maybe we can do this.

The SQLAlchemy `Row` already has `__getattr__` through `BaseRow` so if we add it to asyncpg `Record` then it should be ok for all drivers.

Simple PR for this: https://github.com/encode/databases/pull/448S

**Comment by collerek** [comment]
Please update to 0.5.5 for an immediate fix.

**Comment by bustbr** [comment]
thank you.
