### ISSUE TITLE
Specify pool size during connect

### ISSUE THREAD

**Issue by szelenka** [encode/databases#45]
The default asyncpg pool size is 10, it'd be nice to be able to specify the pool size (and other pool options) during initialization through the databases package during the .connect() call:
https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg-api-pool

It seems there's no options to flow kwargs to the backend.connect() call:
https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L38

Not sure how that would impact mysql and sqlite, but I'm sure they may have similar kwargs which may be useful

**Comment by tomchristie** [comment]
Yup good call. The SQLite backend doens't yet have connection pooling, but `min_size`, `max_size` and `ssl` options all make sense for both the PostgreSQL and MySQL cases.

**Comment by tomchristie** [comment]
Now available as 0.1.7 👍

https://github.com/encode/databases#connection-options
