### ISSUE TITLE
Dependency on sqlalchemy should include asyncio extra

### ISSUE THREAD

**Issue by musicinmybrain** [encode/databases#469]
Since this library uses async API’s from `sqlalchemy`, it should depend on `sqlalchemy[asyncio]` to ensure all necessary dependencies are installed.

Without this, `ValueError: the greenlet library is required to use this function` occurs on platforms where a `greenlet` binary wheel is not available on PyPI; on those platforms, `sqlalchemy` does not depend on `greenlet`, but its `asyncio` extra does.

See [this Fedora issue](https://bugzilla.redhat.com/show_bug.cgi?id=2012590) for full details and discussion.

I will be happy to provide a PR.

**Comment by aminalaee** [comment]
Hey, thanks for looking into this.

I'm just confused why we need to depend on sqlalchemy with asyncio extra requirement? This project does not use the async features of the sqlalchemy.

**Comment by musicinmybrain** [comment]
You’re right. It took me a while to finish following up on the issue, and I didn’t remember (or re-read) the details well enough. In fact, there were two things going on:

- `sqlalchemy` (without extras) depended on `greenlet` on only some platforms (but the `asyncio` extra always depended on it)
- In some `1.4.x` versions of `sqlalchemy` prior to 1.4.26, importing `sqlalchemy.dialects.mysql` unconditionally imported `greenlet` even though it was only supposed to be a hard dependency for the `asyncio` extra. That was a problem for `databases` on those platforms where `sqlalchemy` did not depend on `greenlet` by default.

In fact, no change is required here. Sorry for the distraction!

**Comment by aminalaee** [comment]
No worries.
