### ISSUE TITLE
More query examples for SQLAlchemy n00bs

### ISSUE THREAD

**Issue by florimondmanca** [encode/databases#47]
Hi all,

I've started messing around with Databases to see how it could work with [Bocadillo](https://github.com/bocadilloproject/bocadillo). It looks quite promising, but there are a few issues I encountered while getting started.

Being not very familiar with SQLAlchemy, I had quite a hard time finding resources to learn the syntax mentioned in the README (SQLAlchemy Core). I used SQLAlchemy with Flask in the past but I think it had a different syntax (e.g. `db.commit()`, etc) which doesn't seem to be the one used here.

I also found that the docs for [SQLAlchemy Core](https://docs.sqlalchemy.org/en/latest/core/) the README links to are quite cryptic for new starters.

Do you think there could be more code examples? Especially about the following:

- How to perform a filter using a `WHERE` clause: `notes.select().where(id=1)`?
- Error handling, e.g. what happens when trying to retrieve a row that doesn't exist
- Accessing the ID (and perhaps full data) of the last inserted row

For what it's worth, I'd be glad to help out with this — does anyone have good introductory resources to SQLAlchemy Core aside from the official docs?

**Comment by tomchristie** [comment]
Yep to all the above. We may need to expand beyond a single README page to cover this well, perhaps even a tutorial.

The “expression language tutorial” is probably something we should link to, also. https://docs.sqlalchemy.org/en/latest/core/tutorial.html

**Comment by tomchristie** [comment]
Short answers, since we're here. Some tighening up in #50 is relevant to this.
>  what happens when trying to retrieve a row that doesn't exist

`fetch_one` returns `None`, once #50 is in and release.

>  Accessing the ID (and perhaps full data) of the last inserted row

`.execute` returns the last cursor ID, which is what you need to inserts.

**Comment by tomchristie** [comment]
Folding this into #57

**Comment by tomchristie** [comment]
Welcome to add comments there with anything else we ought to be addressing in the docs!
