### ISSUE TITLE
What does execute return?

### ISSUE THREAD

**Issue by murata100** [encode/databases#476]
Please specify in the document.

[Database Queries](https://www.encode.io/databases/database_queries/#queries)

```python
# Execute
query = notes.insert()
values = {"text": "example1", "completed": True}
what_is_this_1 = await database.execute(query=query, values=values)

# Execute many
query = notes.insert()
values = [
    {"text": "example2", "completed": False},
    {"text": "example3", "completed": True},
]
what_is_this_2 = await database.execute_many(query=query, values=values)
```

What do the following values represent?
- what_is_this_1
- what_is_this_2

**Comment by aminalaee** [comment]
I think this wasn't documented because the return type is dynamic depending on the database and driver.

Now you're passing `insert` to the execute so typically that would be an integer of number of records inserted?

**Comment by murata100** [comment]
```
xxxs = sqla.Table(
    "xxxs",
    metadata,
    sqla.Column("id", sqla.Integer, primary_key=True),
    ...
```

database.execute returns
==================

UPDATE xxxs SET
----------

- `mysql+pymysql://` returns: Number of updated records
- `sqlite://` returns: Number of updated records

INSERT INTO xxxs
------------

- `mysql+pymysql://` returns: Primary key value of inserted record (automatic numbering)
- `sqlite://` returns: Primary key value of inserted record (automatic numbering)

**Comment by aminalaee** [comment]
Yes that is the expected output.

**Comment by murata100** [comment]
> return type is dynamic depending on the database and driver.

Will it be documented?

It should be written that it is database and driver dependent.
