### ISSUE TITLE
getting ValueError: Port could not be cast to integer value as 'xyz' if using '#' in password

### ISSUE THREAD

**Issue by MattMacs** [encode/databases#511]
I've encountered the error mentioned in the title if I try to connect to a database and the password contains a '#'.

**Comment by mryoho** [comment]
Hey @MattMacs I'd say this is a duplicate of this: https://github.com/encode/databases/issues/145

The solution is to use `urlib.parse.quote()` and do something like this:

**Comment by MattMacs** [comment]
Thanks, I'll give it a try.
