### ISSUE TITLE
SQLAlchemy 2.0

### ISSUE THREAD

**Issue by immanelg** [encode/databases#530]
Will there be support for SQLAlchemy 2.0 or I should just use it directly?

**Comment by tarsil** [comment]
@madkinsz Apologies as missed this one. So as far as I could understand, its not planned to give support to SQLA 2.0?

**Comment by Kludex** [comment]
We need someone to maintain this package. :shrug:

**Comment by Kludex** [comment]
I'm not able to review a PR with that bump...

Any of you are? @rafalp @aminalaee

**Comment by rafalp** [comment]
If PR's comes up that bumps SQLAlchemy support to 2.0, I'm fine with it. But I have no resources to develop one myself.

**Comment by tarsil** [comment]
@rafalp @Kludex no worries. Give me a few days and I will have a look and open a PR with a possible integration with SQLA 2.0

We are looking at possible backwards incompatible changes. Last time I tried a few things were changed internally within SQLA.

**Comment by Kludex** [comment]
Cool. :+1: 

Thanks. :pray:

**Comment by tarsil** [comment]
No problem. I have products depending of databases and having the support for 2.0 we can leverage python 3. 2.0 does not support python 2 anymore.

**Comment by BulinLiang** [comment]
I set a default value for the date and name when defining the data field, but when adding a record, the default value was not created. Here is the code.
~~~python
import sqlalchemy as sa 
User = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("name", sa.String(), default="no_name"),
    sa.Column("created_on", sa.DateTime(), default=datetime.now, server_default=sa.func.now(), index=True)
)

db = Database('postgresql+asyncpg://xxx:xxx@localhost/sqlmodel')

async def create():
    query = User.insert()
    await db.execute(query=query, values=dict(version=0.12))

await db.connect()
await create()
~~~
Hope you can help me, thanks

**Comment by BulinLiang** [comment]
I set a default value for the date and name when defining the data field, but when adding a record, the default value was not created. Here is the code.
~~~python
import sqlalchemy as sa 
User = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("name", sa.String(), default="no_name"),
    sa.Column("created_on", sa.DateTime(), default=datetime.now, server_default=sa.func.now(), index=True)
)

db = Database('postgresql+asyncpg://xxx:xxx@localhost/sqlmodel')

async def create():
    query = User.insert()
    await db.execute(query=query, values=dict(version=0.12))

await db.connect()
await create()
~~~
Hope you can help me, thanks

**Comment by samuela** [comment]
any update on this issue? I'd really like to use slack-sdk which depends on `databases` but cannot due to this version constraint

**Comment by zanieb** [comment]
@samuela there is #539 but it has unaddressed questions and could use another contributor

**Comment by samuela** [comment]
Thanks @zanieb ! I ended up finding a workaround for the time being

**Comment by caarmen** [comment]
@samuela Could you share some details of your workaround? 🙏🏻

**Comment by zanieb** [comment]
@caarmen they removed the package entirely as seen in [f9236b3](https://github.com/samuela/nixpkgs/commit/f9236b37e820e0ed8197f1aed7d908c6b6fc73bd)

**Comment by ImEins** [comment]
Can you guys tell us if you plan to add support for sqlalchemy 2.0 ?

**Comment by zanieb** [comment]
@ImEins there is no maintainer that is going to implement it as this time. I will review a contribution with support.

**Comment by ansipunk** [comment]
We did this. #540. Is there a timeframe for a release? @tomchristie

**Comment by tarsil** [comment]
@ansipunk there is one PR opened yesterday that requires some attention. Hopefully today or tomorrow can be merged and we can perform a release.
