### ISSUE TITLE
Support for SQLAlchemy ORM

### ISSUE THREAD

**Issue by Biskit1943** [encode/databases#76]
Hi,

are you planning on supporting SQLAlchemy ORM?

This would be very helpful for users with less knowledge about database design.

**Comment by tomchristie** [comment]
No. There’s no *simple* way of rebuilding SQLAlchemy ORM on top of databases.
We have https://github.com/encode/orm as a first pass on a higher level abstraction, and I’d be very happy to see other projects take up ORMs on top of databases, but I’ve no plans myself on replicating SQLAlchemy on top at this point in time.
