### ISSUE TITLE
Don't require explicit `await database.connect()`

### ISSUE THREAD

**Issue by tomchristie** [encode/databases#8]
We should lazily establish the connection pool as needed.

**Comment by tomchristie** [comment]
Actually it's not obvious if that'd be best or not.

Forcing explicit connection is a good way to ensure correct setup. If we just lazily establish the connection pool, then eg. it's easier to accidentally omit startup/shutdown events when integrating `databases` with a web framework.

**Comment by vltr** [comment]
> Forcing explicit connection is a good way to ensure correct setup.

I agree. There was no single async service I made (either using Twisted or "now" with asyncio) that didn't required explicit connection handling in a use cycle ... Of course, you can always use the `NullPoll` with Postgres behind pgBounce, but not everyone deploys that strategy into production.

There are good patterns to be used out there to handle this, not to mention the `@transaction` and context managers already implemented to do that in the package. :+1: 

> it's easier to accidentally omit startup/shutdown events when integrating `databases` with a web framework.

What do you mean? Leave a connection open after the request lifecycle is finished or leave the database open when shutting down the server (assuming it's an asyncio server) ?

**Comment by tomchristie** [comment]
I mean if we force explicit connects, then it's also more likely that users will remember to use explicit disconnects too.

(If your test cases make sure to startup/shutdown the web application then this ties in nicely with making sure that `force_rollback` runs at the end of every test case.)

Eg. in Starlette we'd expect users to integrate like so:

```python
@app.on_event('startup')
async def startup():
    await database.connect()

@app.on_event('shutdown')
async def shutdown():
    await database.disconnect()
```

**Comment by tomchristie** [comment]
Anyways let's close this issue off. We're good as we are.

Thanks for the extra feedback on it! 😄

**Comment by vltr** [comment]
The example you gave is exactly what I had in mind (relative to asyncio servers). And no need to thank me, we really need some effort on this (databases, ORMs, etc). I would not say that we (developers) feel "abandoned" in the asyncio database special area, but the ecossystem is really not that rich when it comes to that. I hope this changes in the future :wink:

**Comment by Congee** [comment]
Is there any existing option to enable lazy loading rather than me implementing it from scratch? 🤔
