### ISSUE TITLE
Question regarding custom SQLAlchemy types

### ISSUE THREAD

**Issue by steinnes** [encode/databases#80]
For a couple of years I've used some UUID -> str custom type recipe, which basically revolves around importing and extending `UUIDType` from `sqlalchemy_utils`.

The entirety of the recipe is basically:
```python
from sqlalchemy_utils.types import UUIDType

class UUIDString(UUIDType):
    def process_result_value(self, value, dialect):
        if value is None:
            return value
        return str(value)
```

The only point is to make UUID columns to on models convert to the string representation of the UUID, during for example serialization to JSON because the JSON serializers usually don't like bytes :-)

When using one of my existing SQLAlchemy models and trying out this lovely project, I consistently ran into an issue with accessing UUID columns.

Example:

```python
class SomethingModel(Base)
    id = Column(UUIDString, default=lambda: str(uuid.uuid4()), primary_key=True)
    field = Column(String, nullable=False)
```

```python
In[1]: await db.connect()
In[2] tbl = SomethingModel.__table__
In[3] recs = await db.fetch_all(tbl.select())
In[4] r = recs[0]
In[5] r['id']

TypeError                                 Traceback (most recent call last)
<ipython-input-3-31a8ef0c7445> in <module>
----> 1 r.get('id')

~/w/my-api/venv/lib/python3.7/_collections_abc.py in get(self, key, default)
    658         'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
    659         try:
--> 660             return self[key]
    661         except KeyError:
    662             return default

~/w/my-api/venv/lib/python3.7/site-packages/databases/backends/postgres.py in __getitem__(self, key)
    112
    113         if processor is not None:
--> 114             return processor(raw)
    115         return raw
    116

~/w/my-api/venv/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py in process(value)
   1224             if impl_processor:
   1225                 def process(value):
-> 1226                     return process_value(impl_processor(value), dialect)
   1227
   1228             else:

~/w/my-api/venv/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py in process(value)
    900             def process(value):
    901                 if value is not None:
--> 902                     value = bytes(value)
    903                 return value
    904             return process

TypeError: cannot convert 'UUID' object to bytes
```

After an embarrassingly long debugging session, I got this working by implementing a `result_processor` method on my custom type to make sure that `process_result_value` on my custom type was called at all:

```python
   def result_processor(self, dialect, coltype):
       return functools.partial(self.process_result_value, dialect=dialect)
```

After adding this method my custom type works, but I feel like this can't be the right way to fix my problem.  I feel like this is probably not an issue with `databases`, but since I encountered it only after attempting to use it, and as far as I can tell the "standard" `process_result_value` method was never entered or looked for, I thought I'd ask for help here.

**Comment by tomchristie** [comment]
Okay, thanks.
I don't know.
I'd be happy to see the behavior change to take `process_result_value` into account as well if that's the right thing to do, but it might need a bit of digging into SQLAlchemy to see exactly what behavior it uses for queries.

**Comment by steinnes** [comment]
Thanks for reading and reacting.

I think this should just be closed for now.

I spent a few minutes browsing the custom types documentation of SQLAlchemy today (with a clearer head than yesterday), and it seems the `bind_processor` and `result_processor` interface which returns callables is the recommended approach when implementing a new type. (https://docs.sqlalchemy.org/en/latest/core/custom_types.html#creating-new-types).  Why the approach for modifying existing types (https://docs.sqlalchemy.org/en/latest/core/custom_types.html#augmenting-existing-types) has a different interface is slightly confusing, and figuring out why would require a deeper dive into SA internals than I can stomach right now.

If others encounter similar issues, and you want to change the behaviour of the postgres backend, I'd be happy to help in any way I can.

**Comment by tomchristie** [comment]
Thanks @steinnes
