### ISSUE TITLE
How to pass an SSL context to the postgresql backend?

### ISSUE THREAD

**Issue by Lawouach** [encode/databases#84]
Hi,

It appears that databases only accepts a boolean to indicate if you want to connect over TLS to postgresql. But, the [asyncpg driver supports to pass your own context](https://magicstack.github.io/asyncpg/current/api/index.html#connection), which is necessary when you have your own certs.

This make integrating in some environment a showstopper (our environment relies on TLS internally).

Was there a specific issue for not allowing passing a context?

Cheers,
- Sylvain

**Comment by tomchristie** [comment]
See #71

**Comment by Lawouach** [comment]
This sounds like the good basis indeed.

**Comment by Lawouach** [comment]
Hi Tom,

Thanks for being so swift. However, looking at the code, I'm not sure I see how to provide a SSL context myself. It seems it still expects a boolean, right? 

Or am I reading that one wrong?

**Comment by tomchristie** [comment]
You should be able to pass anything accepted by `asyncpg.Connection()` or `asyncpg.create_pool`.

* https://magicstack.github.io/asyncpg/current/api/index.html#connection
* https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.pool.create_pool

I believe `ssl` accepts either an `SSLContext` or a boolean.

**Comment by Lawouach** [comment]
Totally! I misread the code :)

Sorry. Thanks again for the speed :)
