### ISSUE TITLE
How to contact you folks?

### ISSUE THREAD

**Issue by Lawouach** [encode/databases#86]
Hi,

I fully apologise for creating this issue but I'm trying to figure if you have a place to meet (like a slack?). I have questions which don't always warrant an issue or a SO question.

Thanks and sorry again for the spam. Feel free to close :)
- Sylvain

**Comment by tomchristie** [comment]
Currently we don't have a good place for this. 😬

It's possible I'll re-brand the `apistar` discussion board - https://discuss.apistar.org/ - as a general purpose forum, with categories as appropriate.
