### ISSUE TITLE
Why doesn't the PostgreSQL driver use RowProxy?

### ISSUE THREAD

**Issue by Lawouach** [encode/databases#88]
Hi Tom,

Following https://github.com/encode/databases/pull/87, I also discovered that https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L109 is breaking my application because it doesn't respect the actual type and ends up applying the default implementation type of a column.

For instance, if you create a column using UUIDType (from sqlalchemy_utils), it will fail when accessing it because it'll fallback to the default implementation (BINARY or CHAR) to process it. This means that, while the value in the record is a UUID type, the processor tries to convert it as bytes (which doesn't work as expected).

When commenting out that line altogether, meaning no process is applied and the data is returned raw, my application now works fully.

I then noticed that the pgsql driver is the only not using RowProxy from sqlalchemy for records and this issue is the opportunity for me to ask the rationale of that choice :)

Thanks,
- Sylvain

**Comment by Lawouach** [comment]
As a clarification, when I say the code fails, it throws an exception on UUIDType access. For now, I'll revert to sqllite for development's purpose. Once I understand the choice of implementation made, I'll see what is the next course of action. I'd rather keep using databases, because it's clean, but sqlite won't be my actual db so we'll see :)

**Comment by tomchristie** [comment]
The best way to *concretely* progress this would be to submit a failing test case as a pull request.

I’m perfectly happy to consider any pull requests or proposals which then resolve any failures.

> I then noticed that the pgsql driver is the only not using RowProxy from sqlalchemy for records and this issue is the opportunity for me to ask the rationale of that choice

Because it’s not been apparent that it needs to. We have test cases with a bunch of different data types, plus JSON, and a test case with a custom data type, all of which pass. If there’s a case we’re missing then let’s get it included and let’s make sure it’s supported.

**Comment by Lawouach** [comment]
Hi Tom,

> The best way to concretely progress this would be to submit a failing test case as a pull request.

It's not practical not to have a place to chat, the forum isn't really helping getting things _concretely_ moving forward. I had to fallback here to actually exchange with you. Before I can commit time, I need to be able to forage rationale. You could have had a specific use case in mind which is not clear from the code/docs. So lacking a place to discuss, if you don't want issues, is making things harder to quickly moving things in the right direction. 

> I’m perfectly happy to consider any pull requests or proposals which then resolve any failures.

I take your point. But I can't commit to testing all the backends, so would you take a PR that only cares for a specific one?

> Because it’s not been apparent that it needs to.

All these test cases access record properties via items (or index) not attributes as I understand. I think that's why your tests do not reveal these differences. Perhaps the doc could simply state that you only support item accessors accross the board? That's probably in line with the sqlalchemy documentation approach, wdyt?

For now, I'll migrate my code to use key-based accessor rather than attribute based. For the other issue, the type descriptor, I'll likely monkey patch for now as I'm short in time to provide a full investigation of why things happen the way they do with that code. Ultimately, I'd like to have the time to try switching to a RowProxy as for MySQL and SQLite, but without a clear discussion of the pros/cons with you first, it's hard for me to justify the priority of such effort.

Thanks,

**Comment by tomchristie** [comment]
I think there's some confusion here - I don't have any problem with us chatting through something here. What I am saying would progress the issue more is specifics rather than generalities.

A minimal *example* case of something that's not working would help move this ticket forward.

We currently have a test case for a custom datatype, here https://github.com/encode/databases/blob/master/tests/test_databases.py#L480 `test_custom_field`. Adding a similar test case for UUIDField sounds like it might be valuable?

(You don't really need to think about the different drivers youself, since that's all automatically setup in the test cases, just setup `TEST_DATABASE_URLS` as either a single database URL, or a list of comma seperated database URLs.

Aside: I'd suggest we don't mix up item accessors on this ticket, as that's a *seperate* issue from "are custom datatypes correctly supported"

**Comment by Lawouach** [comment]
Sounds all fair indeed.

I'll do my best but as I'm away next week, this may be paused from my side until May. Feel free to close until then.

Thanks.

**Comment by tomchristie** [comment]
Sure thing - let's close this pending an example of a breaking case.
If/when that's filed we can reopen and look again.

**Comment by Lawouach** [comment]
Just a note on the type issue, I did spend some time today exploring the issue (getting tests working in a failing case). It appears there might be an issue with SQLAlchemy Utils default `impl` type for UUIDType. It defaults to `  sqlalchemy.types.BINARY(16)`. But that fails with something like:

```
value = UUID('720999af-0568-4840-9a99-8ccd17c2f7fc')

    def process(value):
        if value is not None:
>           value = bytes(value)
E           TypeError: cannot convert 'UUID' object to bytes

.venv/dbs/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py:943: TypeError
```

I tried to set the `binary` parameter to `False` in the UUITType constructor but to no avail. The reason is that the default `impl` is "somehow" consumed before `load_dialect_impl(dialect)` is called by SA to determine the appropriate type.

When, you switch the class-level `impl` attribute to `CHAR(32)`, then it works nicely. So, for posterity, if someone runs into this issue, my workaround is to do this once somewhere in my app:

```
UUIDType.impl = sqlalchemy.types.CHAR(32)
```

Nothing seems broken on databases side. I can't figure out exactly what was going on with the BINARY type to be fair and I don't intend on investigating further.

**Comment by Lawouach** [comment]
As for accessing record via keys rather than attributes, I will switch to this rather than swell on changing PostgreSQL backend behavior to support attribute access.

**Comment by tomchristie** [comment]
Cool, thanks for the update!

**Comment by mpyatishev** [comment]
Is there a way to fix this without a workaround? I mean maybe it can be done in the `databases` package.

**Comment by mpyatishev** [comment]
In my opinion, it is very strange to have different abstractions for results from MySQL, SQLite and PostgreSQL. While MySQL and SQLite backend returns a RowProxy, PostgreSQL backend returns the Record. So I can't just switch from SQLite to PostgreSQL without overwriting the code. For example, in tests I want to use SQLite and for a normal run - PostgreSQL.

What do you think about the same contract for all backends?
