### ISSUE TITLE
How to test/debug this in terminal / example broken?

### ISSUE THREAD

**Issue by hyperknot** [encode/databases#90]
After many years in the sync land, I'm trying to write my first API in Starlette/databases, and I'm puzzled by the very first task, that is to run something like the official example here:
https://github.com/encode/databases#queries

This does root level `await database.connect()`, which I don't know how is even possible? 

That returns a
```
SyntaxError: 'await' outside function
```

Now I see that IPython has some kind of [async support in 7.x](https://blog.jupyter.org/ipython-7-0-async-repl-a35ce050f7f7) but I don't know how to run that code under IPython either, it returns me the same error.

IPython docs: https://cheat.readthedocs.io/en/latest/python/asyncio.html

**Comment by em92** [comment]
> I don't know how to run that code under IPython either, it returns me the same error.

```
In [1]: %load example.py                                                                      

In [2]: # %load example.py 
   ...: import asyncio 
   ...:  
   ...: print("1") 
   ...: await asyncio.sleep(3) 
   ...: print("2") 
   ...:                                                                                       
1
2

In [3]:                                                                                       
```

Or copy-paste every line to `ipython` terminal.

**Comment by tomchristie** [comment]
Install and run `ipython`, and copy the code into there.
If there's any errors raised then feel free to raise an issue with the specific details.

**Comment by hyperknot** [comment]
OK, with %load it does seem to work, and yet this requirement is never mentioned anywhere. Here are the different ways to run Python code and how it works with async:

`python example.py` SyntaxError: 'await' outside function
`ipython example.py` SyntaxError: 'await' outside function
`ipython` + `run example.py` SyntaxError: 'await' outside function
`ipython` + `%load example.py`: OK
`ipython` + copy and paste from clipboard: OK

So I believe it'd be important to somewhere document that the example codes need to be run via latest ipython + `%load`.

**Comment by tomchristie** [comment]
There's no requirement to use load. Just copy and paste the examples given.

**Comment by hyperknot** [comment]
But from the nature of these examples, you want to edit the database connection syntax (sometimes quite a lot, for example for SSL certificates), and 99% of developer I know would save the example codes into a file. I've opened an issue at IPython about clarifying their docs as well:
https://github.com/ipython/ipython/issues/11700

But here, not even IPython is mentioned once, and this is a relatively new, unknown feature in the Python world, only known by this Medium post: https://blog.jupyter.org/ipython-7-0-async-repl-a35ce050f7f7

**Comment by tomchristie** [comment]
Note added to the README.
I thought we had mentioned it in there already, but turns out that wasn't the case.
