### ISSUE TITLE
Issue with connection to database with postgres (asyncpg)

### ISSUE THREAD

**Issue by kiddick** [encode/databases#92]
There is simplified example extracted from /databases/backends/postgres.py:connect()

```python
import asyncio

import asyncpg

from databases import DatabaseURL

async def run():
    url = 'postgresql://user:password@localhost/dbname'
    pool = await asyncpg.create_pool(str(DatabaseURL(url)))


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

I am getting error `socket.gaierror: [Errno -3] Temporary failure in name resolution` and that's fair since according to https://magicstack.github.io/asyncpg/current/api/index.html#connection-pools accepts **dsn** (str) – Connection arguments specified using as a single string in the following format: `postgres://user:pass@host:port/database?option=value` like that.

So we need to add some note to docs maybe or handle that situation via advanced parsing maybe..

**Comment by kiddick** [comment]
Whoops just read my comment again and that is exactly same format :rofl:

**Comment by tomchristie** [comment]
I didn't understand the issue. Could you try to rephrase it?
What do I need to do to reproduce the issue?

**Comment by kiddick** [comment]
@tomchristie I've figured out what's going on. Details https://github.com/MagicStack/asyncpg/issues/436

**Comment by tomchristie** [comment]
Okay, thanks for the update.
