### ISSUE TITLE
how can i change cursorclass to DictCursor?

### ISSUE THREAD

**Issue by sylvoslee** [encode/databases#94]
how can i change cursorclass to DictCursor?

**Comment by tomchristie** [comment]
I’m okay with having some open ended discussions on the issue tracker, but you’d need to be more clear about what you’re trying to achieve.

**Comment by sylvoslee** [comment]
like pymysql，i can hange cursorclass to DictCursor  as below:
pymysql.connect((host='127.0.0.1',cursorclass=pymysql.cursors.DictCursor)
the defult cursorclass is tuple
when i use databases,by raw SQL queries,how to change the cursorclass to DictCursor
thank you

**Comment by tomchristie** [comment]
Not a supported usage.

**Comment by billsteve** [comment]
def db_datalist_to_dict(datas):
    l = []
    for jd in datas:
        d = {}
        for k, v in jd.items():
            d[k] = v
        l.append(d)
    return l

**Comment by billsteve** [comment]
def db_datalist_to_dict(datas):
    l = []
    for jd in datas:
        d = {}
        for k, v in jd.items():
            d[k] = v
        l.append(d)
    return l

**Comment by mecampbellsoup** [comment]
> Not a supported usage.

Any reason why not? Just no one has done it yet? Seems like without a `DictCursor` configuration option you really cannot use this library (easily) without an ORM :(

**Comment by mecampbellsoup** [comment]
You end up having to write code like this to build your dicts manually:

```
async def get_user(user_id: str) -> User:
    columns = ('id', 'first_name', 'last_name', 'email')
    query = f"SELECT {', '.join(map(str, columns))} FROM iam_user WHERE id = :id"
    result = await database.fetch_one(query=query, values={'id': user_id})
    record: dict = dict(zip(columns, result))
    return User(**record)
```
