### ISSUE TITLE
Support for RETURNING

### ISSUE THREAD

**Issue by LKay** [encode/databases#98]
Is there any way to make use of `RETURNING` statement on insert to get all defaults for columns that are set on the db server? In the documentation for SQLAlchemy Core there is method `return_defaults()` (https://docs.sqlalchemy.org/en/13/core/dml.html#sqlalchemy.sql.expression.ValuesBase.return_defaults) which if applied should return all columns that were not provided and had default set.

According to issue #55 `database.execute` returns only a pointer to the last record (usually id of inserted record), so executing this doesn't work:

```python
stmt = table.insert().values(data='newdata').return_defaults()

result = await database.execute(stmt)

server_created_at = result.returned_defaults['created_at']
```

Is there any way around it or is it absolutely necessary to make two calls to the database to get newly inserted record with all defaults assigned?

**Comment by tomchristie** [comment]
The best thing to progress this would be for someone to come up with an API proposal. How would this look with a raw SQL statement? Are there other RETURNING cases we should be dealing with?

**Comment by LKay** [comment]
The mentioned `return_defaults()` expression works fine when the query is executed through SQLAlchemy Core directly as per documentation. Then the result of execution such query has a property `returned_defaults` which is a dict of all defaults returned from database backend. 

Let's say there is a table:

```sql
CREATE TABLE example (
  id UUID NOT NULL DEFAULT uuid(),
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
```

Then on insert the raw query would look like:

```sql
INSERT INTO example (name) VALUES ("foo") RETURNING id, created_at;
```

Then the result of that would return something like:

```
id                                   | created_at
========================================================================
1e8e09bb-24af-4596-9280-a0e63f397042 | 2019-05-01 00:00:00.000000 +00:00
```


It look like the query is constructed ad executed correctly and it's just the way it's handled inside async executor.

**Comment by euri10** [comment]
it seems to work fine @LKay , I just pushed a branch that tests it minimally, does that help ?
https://github.com/euri10/databases/tree/returning

**Comment by gvbgduh** [comment]
Hey @LKay, `execute` like commands do not receive response from the db, you need to use the `fetch` like ones to get results back from `RETURNING`. It can be `fetch_one`, `fetch_all` etc.

**Comment by tomchristie** [comment]
Closing on the assumption that `RETURNING` statements work okay with `fetch_one`/`fetch_all` - happy to reopen/reconsider, if that's not the case.
