### ISSUE TITLE
Accessing UUID column results in error

### ISSUE THREAD

**Issue by LKay** [encode/databases#99]
Like the title says the error is thrown when I am trying to access the column which stores UUID value. I have postgres at the backend and my table definition looks like this:

```python
table = sa.Table(
    "user",
    metadata,
    sa.Column("user_id", pg.UUID(as_uuid=True), nullable=False, default=uuid4(), primary_key=True),
    sa.Column("name", pg.TEXT, nullable=False),
    sa.Column("created_ts", pg.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.now())
)
```

Then if I try to fetch a record and access `user_id` attribute:

```python
user = await database.fetch_one(
    table.select().where(table.c.user_id == user_id)
)

id = user["user_id"]
```

This throws an exception with message: `'UUID' object has no attribute 'replace'`. Accessing attributes of other types, such as `str`, `bool`, `datetime` works just fine. Seems like `UUID` instance is being treated as string and mapper tries to parse it instead of returning directly (because of `pg.UUID(as_uuid=True)`).

**Comment by euri10** [comment]
I was havin the same issue as you @LKay and solved it by passing `as_uuid=False` which obviously I find super counterintuitive since sqlalchemy says:
```
:param as_uuid=False: if True, values will be interpreted
         as Python uuid objects, converting to/from string via the
         DBAPI.
```
then you got asyncpg handling postgres uuid as python uuid automatically, according to https://magicstack.github.io/asyncpg/current/usage.html#type-conversion

**Comment by LKay** [comment]
I figured that out, although it's not clearly explained as you mentioned. Thanks for pointing that out anyway!
